### ISSUE TITLE
Authorize fails if shipping address isn't entered

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#1]
If I enter my shipping address data explicitly, then I can place the order, but if I leave it to use billing address, not all of the data fields are being filled in.

In case it is store configuration, I've added you as an Admin user to http://wptest.mageklarna.com/wp-admin

![no shipping address](https://cloud.githubusercontent.com/assets/15654455/22370668/97852932-e460-11e6-810d-04c7974af339.png)

Error from Splunk:
	1/27/17
7:13:47.000 AM	
{	[-]	
  	 exception:	 com.klarna.ocay.exception.OrderDataMismatchException: Not matching fields: [shipping_address.given_name, shipping_address.family_name, shipping_address.postal_code, shipping_address.city, order_amount, Incorrect number of items in the cart. Expected: 2, Actual: 3]
	at com.klarna.ocay.domain.session.Session.findDifferences(Session.java:179)
	at com.klarna.ocay.validation.SessionValidator.lambda$sessionDataIsTheSame$0(SessionValidator.java:112)
	at com.klarna.ocay.validation.SessionValidator.lambda$validate$18(SessionValidator.java:358)
[missing shipping json.txt](https://github.com/krokedil/klarna-payments-for-woocommerce/files/735196/missing.shipping.json.txt)

**Comment by slobodan** [comment]
Fixed in develop branch
