### ISSUE TITLE
Refund amount off by 1 penny when sent to Klarna

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#10]
1. Create an order, capture it, and do a partial refund, see http://wptest.mageklarna.com/wp-admin/post.php?post=408&action=edit

refunded in Woo:
Refunded:		-$89.89

2. See Klarna order (via Postman):

  "refunds": [
    {
      "refunded_amount": 8900,
      "refunded_at": "2017-02-07T16:58:45.709Z",
      "description": "",
      "order_lines": []
    }

![refund off by penny](https://cloud.githubusercontent.com/assets/15654455/22702011/4d282d8c-ed2d-11e6-8267-c23fdd2b0dd1.png)

**Comment by slobodan** [comment]
This one is order management plugin issue, fixed it there, closing the issue

**Comment by kristibarbosky** [comment]
Tested successfully, see http://wptest.mageklarna.com/wp-admin/post.php?post=417&action=edit

Note: when calculating the refund amount in Woo admin, Woo's calculations don't always add up correctly (due to rounding), see attached screen shot example.  So per Slack thread below, the KP plugin sends just amount and reason to Klarna.

Closing this ticket.


slobodan [9:27 AM] 
we don't manage that, you just set refunded quantities for each item to match order quantity?

[9:27]  
WC is stupidly bad at rounding, because they round full order amount and use non-rounded item amounts for calculation

[9:27]  
but display item amounts rounded

[9:28]  
and obviously use them rounded for this as well

slobodan [9:28 AM] 
yep, that's 100% handled by WooCommerce

[9:28]  
OK, for now

[9:29]  
because currently we don't send order items that are refunded

[9:29]  
but only amount and reason

[9:29]  
I will investigate if we can do this, for later version

kristi.barbosky [9:29 AM] 
ok, so as long as klarna refund amount == woo refund amount, we're good then for this ticket

slobodan [9:29 AM] 
so, for now, merchants should only use amount and reason fields, and type them in manually

[9:29]  
it is

![woo refund order totals](https://cloud.githubusercontent.com/assets/15654455/22745755/a5c12968-edef-11e6-9696-afb99a0eda13.png)
