### ISSUE TITLE
Review KP implementation again to determine if the 1000's of load calls (happens only with some themes) could be avoided

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#100]
A few themes seem to cause problems with KP where 1000's of load JS calls are triggered to Klarna.  (Perhaps is this caused by the tab's on focus load call, which was done to sync when customers try to place orders within 1 session across multiple browser tabs.)   Could this be implemented differently to coordinate better with more themes?

**Comment by kristibarbosky** [comment]
Also review relating to https://wordpress.org/support/topic/klarna-payments-window-disappears/#post-10725223

**Comment by NiklasHogefjord** [comment]
This issue should be fixed now. Included in the v1.6.3 release. Waiting on response from merchant before closing the issue.

**Comment by kristibarbosky** [comment]
Themes that we've encountered the issue with so far: "UnderStrap Child" & "Fastor"
