### ISSUE TITLE
float instead of int for surcharge fee on create_order [PI-520]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#101]
{ "type" : "surcharge", "reference" : "Fee", "name" : "Klarna Gebühren", "quantity" : 1, "unit_price" : 146.91176470588238, "tax_rate" : 0, "total_amount" : 146.91176470588238, "total_discount_amount" : 0, "total_tax_amount" : 0 } ],

Could anything in this function be sending the number as a float instead of an int?
https://github.com/krokedil/klarna-payments-for-woocommerce/blob/master/includes/class-wc-klarna-payments-order-lines.php#L244

**Comment by kristibarbosky** [comment]
I've requested to find out which plugin is used to configure this fee.

**Comment by NiklasHogefjord** [comment]
I think that this is something that we should fix in the KP plugin. We need to add round() to ensure what kind of numbers we pass to Klarna.

**Comment by NiklasHogefjord** [comment]
This issue should be fixed now. Is there a way for you to test this again @kristibarbosky?

**Comment by kristibarbosky** [comment]
I have requested the affected merchant to upgrade to v1.6.3 and retest.
