### ISSUE TITLE
Support pricing determined via the 'Measurement Price Calculator' plugin [PI-524]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#102]
Can the Woo KP plugin support prices determined via this plugin? https://woocommerce.com/products/measurement-price-calculator/

Currently, KP create_session results in a BAD_VALUE error:
"correlation_id" : "e481713a-d3b2-4689-8c92-57600aa9441b"

{
        "quantity" : 0.5,
        "unit_price" : 2120,
        "tax_rate" : 0,
        "total_amount" : 1060,
        "total_tax_amount" : 0,

  "body" : {
      "error_code" : "BAD_VALUE",
      "error_messages" : [ "Bad value: order_lines[1].total_amount" ],

**Comment by NiklasHogefjord** [comment]
@kristibarbosky  I think it can. Let me test this tomorrow and see if it looks ok.

**Comment by kristibarbosky** [comment]
Closing per confirmation from Klarna implementation advisor; thanks for the support!
