### ISSUE TITLE
KP not loading due to Uncaught TypeError klarna-payments.js#L285 [PI-541]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#107]
klarna-payments.js?ver=1.6.2:285 Uncaught TypeError: Cannot read property 'replace' of undefined
at Object.getSelectedPaymentCategory (klarna-payments.js?ver=1.6.2:285)
at klarna-payments.js?ver=1.6.2:217

from:

https://github.com/krokedil/klarna-payments-for-woocommerce/blob/7b9a35748b1250f8982d1e09d9699692733deb4c/assets/js/klarna-payments.js#L285

I assume this is a theme dependent problem, since I can't recreate the problem on my test store using Storefront theme, but logging the ticket in case we can help/improve  this.

**Comment by NiklasHogefjord** [comment]
Do you know what theme that is used on this site?

**Comment by kristibarbosky** [comment]
Themes that we've encountered the issue with so far: "UnderStrap Child" & "Fastor"

**Comment by kristibarbosky** [comment]
Unfortunately I don't know the theme, but I'll check to see if my co-worker knows.

**Comment by NiklasHogefjord** [comment]
Closing this since we don't know what theme is causing the issue.
