### ISSUE TITLE
Could we improve KP to mandate that address data on authorize & create_order calls always match? [PI-528]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#109]
Reviewing "session_id" : "5aa09513-0363-5566-bf42-84a2d2115349",
 from Oct 16th, shows an issue where that an NL merchant has some customizations (likely another plugin) affecting/refining/cleansing address data.   The postal code address data is changed (to remove the whitespace character) between the Klarna authorize call and the create_order call, causing errors when trying to create the Klarna order.  The Woo order is created in Pending status in Woo, but it is not created in Klarna due to an error.  I can not currently recreate this in my test store as I don't know which address cleansing or shipping plugin was used, but could we improve KP to mandate that address data on authorize & create_order calls always match? 

"body" : { "error_code" : "BAD_VALUE", "error_messages" : [ "Not matching fields: [billing_address.postal_code, shipping_address.postal_code]" ], "correlation_id" : "68d7ba05-cc3c-44b9-a89e-cdd178203362" }

**Comment by kristibarbosky** [comment]
@MichaelBengtsson - another NL merchant is having this same issue and hoping to get a resolution prior to going live with KP.  I've requested Woo admin access to a test store & the plugin used that is changing the address data.

**Comment by NiklasHogefjord** [comment]
We have added a filter to be able to remove whitespaces from postal numbers sent to Klarna - f1b507ec2fa9776eb8e6d6fbcc75dc9b9db4767a. This is included in the v1.6.3 release.

This feature can be activated like this (in functions.php or in a separate plugin):
`add_filter( 'wc_kp_remove_postcode_spaces', '__return_true' ); `

I think that is what we can do at the moment to solve the issue.

**Comment by kristibarbosky** [comment]
The Klarna delivery associate confirmed that this code is working well.  Also, the developer who made the plugin added the code snipped to his plugin so the conflict should be solved in the future.
