### ISSUE TITLE
When updating an order, update notes are repeated.

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#11]
Updated an order to reduce order quantity of 1 order line time.  The update notes were repeated 4 times, see attached. 

![order update notes](https://cloud.githubusercontent.com/assets/15654455/22705614/414b285e-ed3a-11e6-8eef-eb25ef34dcd5.png)

**Comment by slobodan** [comment]
Could be that I'm doing something wrong, but I can't reproduce this. Tried decreasing quantity of multiple items at once, and for only one item, both times it resulted in only one order note.

**Comment by kristibarbosky** [comment]
Order notes are now matching updates.  The "Klarna order updated." may still be repeated but it matches an order update (e.g. one note when the order item quantity is update and another note for when the order total is updated").
