### ISSUE TITLE
Add support for Canada for KP

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#110]
Update KP config settings to include support for currency=CAD & purchase_country=ca
(I've updated MID N100150 to support CAD for testing).

**Comment by kristibarbosky** [comment]
Not yet available for testing; I will reopen when ready for testing.

**Comment by kristibarbosky** [comment]
Can be tested with PK00383 (against EU endpoint for now; but will later be available against NA endpoint).
Canadian KP should work for currency=CAD or (currency=USD, where if the customer's address is Canada, the purchase_country should be set to 'CA' for the session).

**Comment by kristibarbosky** [comment]
Can be tested with PN01233 against NA endpoint

**Comment by MichaelBengtsson** [comment]
Added in version 2.0.0
