### ISSUE TITLE
Make sure that SOFORT payments work as expected

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-payments-for-woocommerce#112]

**Comment by NiklasHogefjord** [comment]
This should be fixed in fc89056cc82c13e77e334782ef6985a98ecc6f50. The Klarna iframe should not be displayed now until all required fields are entered.

Leaving this issue open until we get a response from the German merchant we're in touch with in Krokedil support.

**Comment by kristibarbosky** [comment]
Duplicate of https://github.com/krokedil/klarna-payments-for-woocommerce/issues/95

**Comment by kristibarbosky** [comment]
test passed successfully (confirmed by Klarna DE resource)
