### ISSUE TITLE
Link to documentation in readme is incorrect

### ISSUE THREAD

**Issue by LarsBuur** [krokedil/klarna-payments-for-woocommerce#117]
Not sure what is the correct link.

**Comment by kristibarbosky** [comment]
Thanks for pointing this out @LarsBuur ;  we'll get it updated.  Here is the link:
https://docs.woocommerce.com/document/klarna-payments/

**Comment by NiklasHogefjord** [comment]
This is fixed in edfb04fe5431c9a2abfe89d3f21a60fbcca5cc33. It will be included in the next release.

**Comment by LarsBuur** [comment]
Thank you. Please note that the link @kristibarbosky posted is different from what is in the commit from @NiklasHogefjord.

**Comment by NiklasHogefjord** [comment]
Hi @LarsBuur, actually it is not.

The link in the readme was never wrong. It was the _Plugin URI_ in the _plugin header_ and the _Docs link_ in the _plugin action links_ that was wrong. They are changed now and the link that @kristibarbosky posted is the one now used in the _Docs link_ in the _plugin action links_ section.
