### ISSUE TITLE
Show validation errors

### ISSUE THREAD

**Issue by LarsBuur** [krokedil/klarna-payments-for-woocommerce#118]
I have Setup the klarna payment plugin 1.6.3 in woocommerce 3.5.2 on wp 5.0.0

I am still in test/playground modus. 

When some fields/details that are required by klarna payments are missing then the button to continue (see attached image) is disabled. However I am unable to see what is missing / what throws the validation error and that leads to poor customer experience - and probably lost sales.

Is there any way to display the validation errors?
![screenshot 2018-12-19 at 13 01 19](https://user-images.githubusercontent.com/3585707/50219342-31aae200-038f-11e9-9064-72b1a51cab6a.png)

**Comment by LarsBuur** [comment]
I should add that there is no validation errors list in the top of the page. There are no way of telling why the klarna payment button is inactive.

**Comment by NiklasHogefjord** [comment]
Thanks for the report. We will discuss this together with Klarna.

If you need support to solve this specific issue, please get in touch with us at support@krokedil.com.

**Comment by LarsBuur** [comment]
> Thanks for the report. We will discuss this together with Klarna.
> 
> If you need support to solve this specific issue, please get in touch with us at [support@krokedil.com](mailto:support@krokedil.com).

@NiklasHogefjord: I am not sure why Klarna would need to be involved in this - but that´s not for me to decide.  

It´s basically a need for the plugin to report that it is not satisfied The current solution leads to bad user experience.

**Comment by MichaelBengtsson** [comment]
@LarsBuur We have a fix for this in the develop branch of the plugin at the moment. Testing to make sure it works properly, aswell as checking with Klarna if this is an acceptable way of dealing with this issue.
