### ISSUE TITLE
phone is set to email instead of phone

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#123]
‘email’ => stripslashes( $posted_data[‘billing_email’] ),
‘phone’ => stripslashes( $posted_data[‘shipping_email’] ),

shipping phone field is incorrectly set to email

https://github.com/krokedil/klarna-payments-for-woocommerce/blob/1d8eb85236e777069797030657f8d365af1ce31f/includes/class-wc-gateway-klarna-payments.php#L994

**Comment by NiklasHogefjord** [comment]
Thanks for the report. This should be fixed in 986e997baf43ee81b0c4ec129b797162d9ce9024.
