### ISSUE TITLE
Make logo, title and description changeable in positioning

### ISSUE THREAD

**Issue by a-larsson** [krokedil/klarna-payments-for-woocommerce#130]
In the checkout:

The client asks:
Ideas: Logo first than title, and below second line description please
make logo optional.

Is it possible to make logo, title and description changeable in positioning from the plugin settongs?

**Comment by MichaelBengtsson** [comment]
Closed. We add the logo and title the same way as WooCommerce does it with for example the PayPal gateway. Due to this it is up to the individual merchant to configure there theme to display this the way they want to.
