### ISSUE TITLE
409 error when company name is entered AND both billing address & shipping address are entered [PI-755]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#132]
Recreated in test store with latest v1.6.4 version

error_code: BAD_VALUEerror_messages: Not matching fields: [shipping_address.organization_name]

![image](https://user-images.githubusercontent.com/15654455/57871965-a36d4780-77d8-11e9-9718-d52ccfd49195.png)

**Comment by MichaelBengtsson** [comment]
Should be fixed in last release.
