### ISSUE TITLE
finalize call for KP (needed for DE Pay Now) [PI-789]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#134]
Even though Woo doesn't have a multi-step checkout with KP, it seems we still need to use the finalize call for KP, see: https://developers.klarna.com/documentation/klarna-payments/integration-guide/authorize#finalize-the-authorization

Reason is that if a customer enters invalid info in Woo checkout (e.g. an invalid postal code, 	 postal_code:	 41460abcd), the funds are withdrawn from the bank account prior to the Woo error.  So the Woo order & Klarna order are not placed, but the funds are withdrawn.  

Recreated with "Online bank transfer"
merchant_id:	 K501112
test order_id=eda8863c-2f68-7afb-818f-14b7ad8f80a0

**Comment by MichaelBengtsson** [comment]
Closed due to the latest releases changing the flow to prevent this.
