### ISSUE TITLE
Gift card amount was included in Klarna order total

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#14]
When an order is placed with KP and a gift card, do not include gift card total in the Klarna order amount, see order: http://wptest.mageklarna.com/wp-admin/post.php?post=394&action=edit
and
https://api-na.playground.klarna.com/ordermanagement/v1/orders/be65a9b3-af6d-4769-914f-f80253033866

**Comment by slobodan** [comment]
@kristibarbosky this is now handled in #15 (smart coupons), OK to close this one?

**Comment by kristibarbosky** [comment]
Closing as this is covered by #15
