### ISSUE TITLE
Could Woo locale be mapped/transformed to Klarna locale using code to support many locales?

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#140]
KP is using RFC 1766 standard
Woo uses ISO 15897

**Comment by MichaelBengtsson** [comment]
Solved in 2790a89fc16bfb1197cf74a7e9d302be074049a2

**Comment by kristibarbosky** [comment]
https://github.com/krokedil/klarna-payments-for-woocommerce/releases/tag/2.1.0
