### ISSUE TITLE
Klarna iframe doesn't display (for US stores) [PI-1008]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#146]
with v1.8.3, the Klarna iframe doesn't display for US stores

Uncaught TypeError: Cannot read property 'given_name' of undefined
    at Object.get_address (klarna-payments.js?ver=1.8.3:252)
    at klarna-payments.js?ver=1.8.3:160

![image](https://user-images.githubusercontent.com/15654455/62885691-84168580-bd07-11e9-8d32-6b593a4c6cd3.png)

**Comment by MichaelBengtsson** [comment]
@kristibarbosky 
I belive this is an issue with US stores due to this line:
https://github.com/krokedil/klarna-payments-for-woocommerce/blob/master/assets/js/klarna-payments.js#L160

Does US KP need adress data at a different step then EU KP does?

**Comment by kristibarbosky** [comment]
Yes, US KP does get address data earlier than EU.

**Comment by kristibarbosky** [comment]
Fixed with v1.8.4 per https://github.com/krokedil/klarna-payments-for-woocommerce/releases/tag/1.8.4
