### ISSUE TITLE
Truncate all reference fields (shipping_reference, surcharge, etc.) to 64 characters [PI-1011]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#149]
Similar to previously resolved issue (https://github.com/krokedil/klarna-payments-for-woocommerce/issues/38), shipping_reference field should also be truncated at 64 characters (https://github.com/krokedil/klarna-payments-for-woocommerce/blob/4ef90e91f97818d1a8a23d8229d59f9e6a5d8ed6/includes/class-wc-klarna-payments-order-lines.php#L745)

**Comment by kristibarbosky** [comment]
Also surcharge reference field please

**Comment by NiklasHogefjord** [comment]
Fixed in 20cc4eb3fe15885e0616355affbec58c6e7e0606
