### ISSUE TITLE
Make sure plugin works with WooCommerce Smart Coupons

### ISSUE THREAD

**Issue by slobodan** [krokedil/klarna-payments-for-woocommerce#15]

**Comment by slobodan** [comment]
Fixed in 'develop' working on update for this for OM plugin

**Comment by slobodan** [comment]
OM plugin updated as well, to preserve smart coupons on order updates

**Comment by kristibarbosky** [comment]
@slobodan - how can I test this ticket since I don't have a copy of the WooCommerce Smart Coupons plugin.  Do you have a version that I could use on my test store?  Or will your testing need to be suffcient?

**Comment by kristibarbosky** [comment]
Tested successfully, see
http://wptest.mageklarna.com/wp-admin/post.php?post=453&action=edit
https://api-na.playground.klarna.com/ordermanagement/v1/orders/f9fd8f18-9e02-4be8-a987-dceb1be1e2ab


{
  "order_id": "f9fd8f18-9e02-4be8-a987-dceb1be1e2ab",
  "status": "CAPTURED",
  "fraud_status": "ACCEPTED",
  "order_amount": 76513,
  "original_order_amount": 76513,
  "captured_amount": 76513,
  "refunded_amount": 0,
    {
      "reference": "Discount",
      "type": "discount",
      "quantity": 1,
      "quantity_unit": "",
      "name": "krist589fc028c9f7d",
      "total_amount": -2500,
      "unit_price": -2500,
      "total_discount_amount": 0,
      "tax_rate": 0,
      "total_tax_amount": 0,
      "merchant_data": null,
      "product_url": null,
      "image_url": null
    }
