### ISSUE TITLE
Add more console logging to debug when KP JS is too optimized and not usable [PI-1033]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#150]
While this issue is now documented (at https://docs.krokedil.com/article/302-klarna-payments-optimizing-your-woocommerce-cart-checkout-when-using-an-iframe-based-checkout), it would make support & debugging easier to have additional logging relating to this issue.

**Comment by NiklasHogefjord** [comment]
Console.log added here 45a0ccacebc662fbbb278358583065391a579a7a

**Comment by NiklasHogefjord** [comment]
Pushed live now.
