### ISSUE TITLE
Klarna session could not be created, "Bad value: order_lines[0].total_tax_amount"

### ISSUE THREAD

**Issue by funtoosh** [krokedil/klarna-payments-for-woocommerce#155]
Hi there,
we are having trouble connecting to Klarna with the plugin, there is an error in the WordPress cart that says "COULD NOT CREATE KLARNA SESSION, PLEASE REFRESH THE PAGE TO TRY AGAIN". Refreshing does, of course, not help. When I check the logs/protocols at Klarna portal, there is an error 400: error_code: BAD_VALUE // error_messages: Bad value: order_lines[0].total_tax_amount … 
Any idea? I checked the thread over here https://github.com/krokedil/klarna-checkout-for-woocommerce/issues/38 and changed the decimal setting from 0 to 2 and back, to no avail …
Cheers, -martin

**Comment by kristibarbosky** [comment]
@funtoosh  - Please create a support case at support@krokedil.com with details for your store, so your specific configuration can be reviewed.

**Comment by funtoosh** [comment]
Kristi, I just sent a mail, thx!

**Comment by MichaelBengtsson** [comment]
Closed after support ticket with customer solved the issue.

Issue was incorrect settup in tax settings.
