### ISSUE TITLE
Error creating session on checkout page load when Default Customer Address is set to "No address"

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#16]
1. Merchant has "Default Customer Address" set to "No address" and thus, when the checkout page first loads, a error "Could not create Klarna session, please refresh the page to try again" is shown 
2. this code can therefore not set the purchase_country:
'body' => wp_json_encode( array(
				'purchase_country'  => WC()->customer->get_country(),
3. If there is no default customer address set, can you pull the purchase country based on the configured KP MID?

	 logger:	 com.klarna.yaco.commons.consolidated.ConsolidatedLogFilter	
  	 merchant_id:	 N100145	
  	 message:	 {
  "correlation_id" : "ad087da5-c9ba-4e6f-8b4e-02b0f35ee099",
  "merchant_id" : "N100145",
  "operation" : "create_session",
  "build_version" : "0.0.1.319",
  "request" : {
    "timestamp" : "2017-02-08T18:20:45Z",
    "method" : "POST",
    "path" : "ocay/merchant/N100145/v1/sessions",
    "headers" : {
      "Accept" : "*/*",
      "Connection" : "keep-alive",
      "X-Forwarded-Proto" : "http",
      "X-Forwarded-Host" : "api-na.playground.klarna.com",
      "User-Agent" : "WordPress/4.7.2; https://gbklarna.wpengine.com",
      "Referer" : "https://api-na.playground.klarna.com/credit/v1/sessions",
      "Host" : "api-na.playground.klarna.com",
      "Accept-Encoding" : "deflate, gzip",
      "X-Forwarded-Port" : "80",
      "X-NewRelic-ID" : "VQIAVFBVDxAEUFRXAAQOXw==",
      "Klarna-Correlation-Id" : "ad087da5-c9ba-4e6f-8b4e-02b0f35ee099",
      "X-NewRelic-Transaction" : "PxQPUwUBDgYBUgUHDwNTUgcEFB8EBw8RVU4aWgpbVgQGVA8FVFkBBlBVAkNKQV1RBVRWAQ8JFTs=",
      "X-Forwarded-For" : "104.130.217.47, 104.130.217.47, 10.226.9.142",
      "Content-Length" : "468",
      "Content-Type" : "application/json"
    },
    "body" : {
      "purchase_country" : "",
      "purchase_currency" : "USD",
      "locale" : "en-US",
      "order_amount" : 79500,
      "order_tax_amount" : 0,
      "order_lines" : [ {
        "reference" : "GBED8011-QNN",
        "name" : "GhostBed Mattress Queen",
        "quantity" : 1,
        "unit_price" : 79500,
        "tax_rate" : 0,
        "total_amount" : 79500,
        "total_tax_amount" : 0,
        "total_discount_amount" : 0
      }, {
        "type" : "sales_tax",
        "reference" : "Sales Tax",
        "name" : "Sales Tax",
        "quantity" : 1,
        "unit_price" : 0,
        "tax_rate" : 0,
        "total_amount" : 0,
        "total_discount_amount" : 0,
        "total_tax_amount" : 0
      } ]
    }
  },
  "response" : {
    "timestamp" : "2017-02-08T18:20:45Z",
    "status" : 400,
    "headers" : {
      "Render-Time" : "18",
      "Klarna-Correlation-Id" : "ad087da5-c9ba-4e6f-8b4e-02b0f35ee099",
      "Content-Type" : "application/json"
    },
    "body" : {
      "error_code" : "BAD_VALUE",
      "error_messages" : [ "Bad value: purchase_country" ],
      "correlation_id" : "ad087da5-c9ba-4e6f-8b4e-02b0f35ee099"
    }

**Comment by slobodan** [comment]
Fixed in 'develop', assigning back to you for testing.

**Comment by kristibarbosky** [comment]
Tested successfully, see http://wptest.mageklarna.com/wp-admin/post.php?post=429&action=edit

Updated plugin provided to merchant as well.
