### ISSUE TITLE
check for KP hashtag on page load [PI-1188]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#162]
to prevent issues when page is reloaded instead of hash tag added

**Comment by NiklasHogefjord** [comment]
We don't want to add this to the plugin. If the customer navigates back to the old url (after purchase) it might trigger the flow to complete purchase again.

Can we close this?

**Comment by kristibarbosky** [comment]
Closing as this is now documented at:
https://docs.krokedil.com/article/155-klarna-payments-introduction#h-H2_1
and https://docs.woocommerce.com/document/klarna-payments/#section-2

Your site must be able to handle anchor links (or URI fragments) correctly. This means that when an anchor link is triggered the browser should not trigger a full reload of the page. You can test this by navigating to one of your website pages, enter a following /#testhash to the url in the browser address bar and then hit Enter. This shall not trigger a full reload of the page.
