### ISSUE TITLE
wc_ajax cause error 500 on "Place Order" action.

### ISSUE THREAD

**Issue by davpirelli** [krokedil/klarna-payments-for-woocommerce#165]
Hi, i've implemented Klarna Payment in my Woocommerce. On the checkout, everyting works correctly, but, when i click "Complete Purchase" on console i see:

`/?wc-ajax=kp_wc_place_order:1 -> Failed to load resource: the server responded with a status of 500 ()`
`kp_wc_place_order error`

Visiting the link _/?wc-ajax=kp_wc_place_order_ i get a JSON with:
`{
"success": false,
"data": "bad_nonce"
}`

On Klarna playground i can see the Create session and Update session log correctly, how can i fix it?

**Comment by kristibarbosky** [comment]
@davpirelli - Please first update to the latest Woo KP release v2.0.3 (https://github.com/krokedil/klarna-payments-for-woocommerce/releases/tag/2.0.3) to see if that resolves the issue.  I do see some errors in the Klarna logs that I expect to be resolved with the latest release.

**Comment by davpirelli** [comment]
Hi @kristibarbosky..i've just updated the plugin to v2.0.3 but still getting the same result. Error 500 in kp_wc_place_order.

**Comment by kristibarbosky** [comment]
Thanks @davpirelli  - I don't see the same errors in the Klarna logs now, but to further debug, could you please open a support request at support@krokedil.com (and provide Woo admin access to a store (a test store if available) where this issue can be reproduced).

**Comment by kristibarbosky** [comment]
Per discussion with Klarna and Krokedil and per above comment, this is best handled via a support@krokedil.com case.
