### ISSUE TITLE
Don't allow B2B (customer.type=organization) for US currently [PI-1235]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#167]
Some US merchants are setting customer type=B2B (or the database is corruptly saving this) and then KP is not successfully displayed (4 US merchants over last 7 days) as Klarna US does not currently support B2B.

**Comment by kristibarbosky** [comment]
per chat, this could be caused by field default setting

**Comment by MichaelBengtsson** [comment]
Fixed in 2.0.4
