### ISSUE TITLE
Reporting in Woo admin for BAD_VALUE create_order failures

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#169]
KP orders fail upon create_order call if data doesn't pass Klarna validation, i.e.:

1. for mismatched data between authorize & create_order, e.g.: "Not matching fields: [Incorrect number of items in the cart. Expected: 4, Actual: 5]"
2. if data amounts don't calculate correctly, e.g.: "Bad value: order_lines[2].total_tax_amount": name: UPS
             quantity: 1
             reference: flat_rate:1
             tax_rate: 700
             total_amount: 495
             total_tax_amount: 41
             type: shipping_fee
             unit_price: 495

Customers get an Oops error and data is available in the Logs app in the Klarna Merchant Portal, but to make it easier for merchants to get visibility and debug this, please add statistics in the Woo admin (similar to KCO fallback orders) based on BAD_VALUE errors.  Hopefully Woo logs already have sufficient logging to support debugging, but good to confirm as well.  thx!

**Comment by muntjaber** [comment]
We have added more thorough logging and means of identifying these kind of issues in WordPress. I am therefore closing this issue.
