### ISSUE TITLE
Can the background of the iframe on checkout page be white instead of gray?

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#17]
Our UI designer requested that the background of the iframe (including the triangle/arrow) be white instead of the current gray, Is this doable?

![gray iframe background](https://cloud.githubusercontent.com/assets/15654455/22796607/fe8d3d6e-eec8-11e6-9731-2e9b2717e697.png)

**Comment by slobodan** [comment]
@kristibarbosky Can't this be done at iframe level? It already has a lot of its own CSS, I don't understand why this rule would be an exception.

**Comment by kristibarbosky** [comment]
@slobodan - we're asking for the gray box around/outside of the iframe to be white (if possible).  Unfortunately we're not currently able to control the color of the iframe background; it is transparent.  We can only control the iframe with the config settings that you've added to the Woo admin, but none of those will affect this.

**Comment by slobodan** [comment]
There's a lot of embeded CSS inside the iframe though, strange that iframe body background can't be set to a color.

Since it can't be set inside the iframe, yes, this is doable (although I am against it, since this is what theme is responsible for) and if we decide to go ahead with it, I recommend having a color picker field rather than hardcode it to white. Thoughts?

**Comment by kristibarbosky** [comment]
@slobodan .  Yes, a color picker is the better approach rather than hardcoding it.  thanks!

**Comment by slobodan** [comment]
Post go live?

**Comment by kristibarbosky** [comment]
actually our UI designer would like to use the white color background for the 1st merchant, so this is go live desired if possible.  the merchant still has some work on their side, so they may not flip the switch exactly on the 15th, so if you a bit longer to do this, that can be ok.

**Comment by slobodan** [comment]
Added option next to other iframe color options. Fixed in 'develop' branch.

**Comment by kristibarbosky** [comment]
Per discussion with Melissa, we will leave the iframe background config option in the Woo admin (as it is already done and a convenience for merchants), but further customizations (including the little gray arrow at the top of the iframe container) is something the merchant would have to customize if desired (not to be included in the plugin).
