### ISSUE TITLE
Reset session after a 409 error

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#170]

**Comment by MichaelBengtsson** [comment]
I believe this has been fixed for a while without this being closed. With a change we did to our logic, if we get any response that is not in the 2xx range, we will throw the session and attempt to create a new one during an update call.

https://github.com/krokedil/klarna-payments-for-woocommerce/blob/master/includes/kp-functions.php#L20-L34

Ill close this now, but if its still an issue for anyone feel free to reopen the issue.
