### ISSUE TITLE
What is Klarna link - add option for merchant customization [PI-1448]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#176]
https://github.com/krokedil/klarna-payments-for-woocommerce/blob/dc6a47f7a003936183765ca9bb70d7d36754c62e/classes/class-wc-gateway-klarna-payments.php#L80

related to: https://github.com/krokedil/klarna-payments-for-woocommerce/issues/164, https://github.com/krokedil/klarna-payments-for-woocommerce/issues/57, https://github.com/krokedil/klarna-payments-for-woocommerce/issues/39

Please also update the link for all regions to klarna.com

**Comment by kristibarbosky** [comment]
per chat today, will reopen to allow merchants to customize this link

**Comment by MichaelBengtsson** [comment]
Closing this since this has been resolved.
