### ISSUE TITLE
Update 'Tested up to WooCommerce version' number

### ISSUE THREAD

**Issue by rolandog** [krokedil/klarna-payments-for-woocommerce#179]
Hello, when trying to upgrade WooCommerce to version 4.0.1 from 3.9.2, I'm greeted with a warning about the possible incompatibility of the _Klarna Payments for WooCommerce_ plugin:

> This is a major update, are you sure you're ready?
> The following active plugin(s) have not declared compatibility with WooCommerce 4.0 yet and should be updated and examined further before you proceed:
> Plugin | Tested up to WooCommerce version
> -- | --
> Klarna Payments for WooCommerce | 3.9.2

Is it safe to upgrade? If so, can you please bump the compatibility number so that other users are not dissuaded to upgrade (and stay up-to date with security fixes)?

**Comment by kristibarbosky** [comment]
please also double check & document required version of WooC (I believe WC version:3.3.5 is not sufficient either)
