### ISSUE TITLE
Indicate Klarna environment (test vs. live) on Woo order [PI-1521]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#180]
Currently a Woo admin could check this at the '_wc_klarna_environment' meta field (using the 'Show Hidden Post Meta' plugin), but to make it easier for merchants, as time permits, could you please enhance the code to indicate the Klarna environment (test/playground vs. live/production) in the Woo order?  thx!

(Created same request for KCO: https://github.com/krokedil/klarna-checkout-for-woocommerce/issues/296)

**Comment by MichaelBengtsson** [comment]
Solved in daa7c2fd8971a8bdad0af39038193bde83ae4e67

**Comment by kristibarbosky** [comment]
thank you for this enhancement! 
![image](https://user-images.githubusercontent.com/15654455/87172052-9d221080-c2a1-11ea-8da7-705f9988b8d4.png)
