### ISSUE TITLE
Forced checkout refresh when checkout URL includes query parameters

### ISSUE THREAD

**Issue by vendidero** [krokedil/klarna-payments-for-woocommerce#182]
Hi there,

I was just debugging some problem concerning Germanized and Klarna Payments. A strange issue has been reported to me that in case a forced guest checkout (through the DOI feature integrated in Germanized) was started, the Klarna Payments Checkout refreshes upon clicking the submit button without submitting the order. Submitting again afterwards will lead to a positive result.

Germanized uses the following checkout URL
http://shop.test/checkout/?force-guest=yes

For testing purposes I have deactivated Germanized and opened that URL directly (after adding a product to the cart) to see whether the problem remains. Even if Germanized was disabled, the problem remains (checkout gets refreshed on first submit). I guess the JS hash-check seems to be the key to the issue: https://github.com/krokedil/klarna-payments-for-woocommerce/blob/master/assets/js/klarna-payments.js#L453

Cheers

**Comment by MichaelBengtsson** [comment]
@vendidero Hi!

This should have been solved in version 2.0.8 of the plugin. Could you test with that version and see if you still have the same issue?
