### ISSUE TITLE
Remove "What is Klarna?" link from payment selector on Woo checkout page & open link in new tab

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#19]
Related to #7 
Until #7 is completely fixed, didn't we decide to remove the "What is Klarna?" link?
And please make the link (https://www.klarna.com/us/pay-over-time) open in a new tab

**Comment by slobodan** [comment]
<img width="472" alt="screen shot 2017-02-12 at 13 56 01" src="https://cloud.githubusercontent.com/assets/129607/22862223/13102652-f12b-11e6-91ea-af5343bd04d4.png">

Now both Klarna image and "What is Klarna" open in new window, link is as described in #7

**Comment by kristibarbosky** [comment]
Looks good.  

![image](https://cloud.githubusercontent.com/assets/15654455/22863454/322e4252-f10e-11e6-8bfa-bb20fd4e4234.png)
