### ISSUE TITLE
filter for order items to fix incompatibilities

### ISSUE THREAD

**Issue by the-infinity** [krokedil/klarna-payments-for-woocommerce#191]
Klarna payments has some issues if it comes to splitted VAT. Here in Germany, VAT of shipping has to be split up proportionately to the cart items. WooCommerce Germanized provides an solution in doing this and having two tax rates for the same line item. Klarna payments fails to read this items, the plugin sends just one VAT value to Klarna backend, and the payment gets rejected because the VAT is wrong. This, by the way, also happens with order fees.

There's another issue with smart coupons: in some cases get_coupon_discount_amount() is 0 after ordering, supposingly because of coupons which can be used several times. Then you have a working Create Session before ordering because before ordering, but after ordering you get get_coupon_discount_amount() = 0. This can be fixed by reading $cart_item->get_total() instead of get_coupon_discount_amount().

Because the first one is a very specific (German) requirement and the second one a very specific issue to smart coupons, I would suggest to add a filter to fix order_lines here: https://github.com/krokedil/klarna-payments-for-woocommerce/blob/master/classes/requests/helpers/class-kp-order-lines.php#L89 . I will add a pull request after writing this report.

**Comment by MichaelBengtsson** [comment]
Sorry for the delay on this, it will be added to the next full release of the plugin. Thank you for the PR.

**Comment by MichaelBengtsson** [comment]
This has now been released with version 2.4.0
