### ISSUE TITLE
Issues with splitted taxes

### ISSUE THREAD

**Issue by the-infinity** [krokedil/klarna-payments-for-woocommerce#193]
If a product has splitted tax values (which is quite common here in Germany for shipping), Klarna Payments just takes one tax rate. This is rejected by Klarna, because the calculation sent to Klarna is not consistent (they just don't know about the second tax rate, and calculating taxes just by one rate gives wrong sums).

**Comment by tschopo** [comment]
When will this be fixed?

**Comment by kristibarbosky** [comment]
this is planned to be worked on hopefully next month; the best that can be done is send tax data in separate order line items (not multiple tax rates within a single physical order line item since isn't supported by Klarna Payments API)

**Comment by cwussmann** [comment]
Is this fixed yet? because on a customers site it doesn't seem to :(

**Comment by montazarr** [comment]
The Klarna Payments API does not have support for split-tax, so we won't be able to fix this issue. I am closing this issue accordingly.
