### ISSUE TITLE
Coupons fail at sending order request

### ISSUE THREAD

**Issue by the-infinity** [krokedil/klarna-payments-for-woocommerce#194]
Coupons which change on using them break the place order request done in https://github.com/krokedil/klarna-payments-for-woocommerce/blob/master/classes/requests/post/class-kp-place-order.php .

Background is WooCommerce Smart Coupons and coupons which reduce on ordering. Before ordering, the coupon has an amount of x euro. After ordering, this changes to x minus order sum (or zero if x < order sum). This leads to two issues:
- all coupons change to value 0 at the order request
- the sum over all products and coupons is now just the sum over all products, which differs from the sum of the order

It's quite fatal because for the user, everything seems ok - it's just the place order request which fails, after all create and update session requests succeed.

**Comment by broksonic21** [comment]
We are also seeing this. Here's my repo. Is there a fix?

https://github.com/krokedil/klarna-payments-for-woocommerce/issues/204

**Comment by MichaelBengtsson** [comment]
This should be solved now with version 2.1.4. If there is still an issue please let me know.
