### ISSUE TITLE
Error when resubmitting an order after a previous error

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#2]
1. Set up cart with a product, click Place Order button, but do not yet accept terms & conditions.
2. Page is reloaded with a message telling customer "You must accept our Terms & Conditions."
3. Accept the terms and Place Order again.
4. An error is returned to the customer "Error processing checkout. Please try again."

Here is the error from Splunk:

	1/27/17
11:50:31.000 AM	
{	[-]	
  	 exception:	 com.klarna.ocay.exception.OrderDataMismatchException: Not matching fields: [order_amount, Incorrect number of items in the cart. Expected: 2, Actual: 3]
	at com.klarna.ocay.domain.session.Session.findDifferences(Session.java:179)

**Comment by slobodan** [comment]
Fixed in develop branch

**Comment by kristibarbosky** [comment]
Tested successfully, see http://wptest.mageklarna.com/wp-admin/post.php?post=403&action=edit
