### ISSUE TITLE
Can order capture succeed after an initial failed capture?

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#20]
1. Submit a pending order that takes many minutes to update, e.g. k+pend-accept-10@klarna.com
2. Before the 10 minutes expire, move the order to "Completed" status, Klarna will failure the capture (because it is still pending).
3. Move the order back to "On Hold" status and then after pending review; the order subsequently does get moved to "Processing" by the plugin.
4. When I try to capture the order a 2nd time by moving it to "Completed" status again, it fails (but doesn't seem to actually go against Klarna to try the capture again according to Splunk).  Can the 2nd capture attempt call Klarna and hopefully succeed?

See http://wptest.mageklarna.com/wp-admin/post.php?post=460&action=edit

**Comment by slobodan** [comment]
Fixed in latest commit (merged to master branch too)

**Comment by kristibarbosky** [comment]
when i move a pending order (still under pending in Klarna), from On Hold to Completed, I'm not getting the order note in Woo that the capture failed.  I think we still need to have that to show the admin that capture failed, right?  http://wptest.mageklarna.com/wp-admin/post.php?post=466&action=edit

**Comment by slobodan** [comment]
Submitted the fix to order management plugin, order note added:

"Klarna order is pending review and could not be captured at this time."

**Comment by kristibarbosky** [comment]
Tested successfully against develop branch.  Order note is now listed:
![could not capture at this time](https://cloud.githubusercontent.com/assets/15654455/23109787/fd6a63a2-f6e9-11e6-99ba-534a8291f536.png)

Order was successfully captured from Processing status (after moving it back to On Hold status after 1st correctly failed capture attempt while the order was still Pending in Klarna.)
