### ISSUE TITLE
Errors aren't handled and end up 404ing

### ISSUE THREAD

**Issue by broksonic21** [krokedil/klarna-payments-for-woocommerce#202]
We are trying to use this and errors aren’t being handled even on our test site w/ just Klarna and WooCommerce installed (and storefront, so no custom theme)

For repro:

* Have Klarna Payments turned on (test mode or live mode)
* Try checking out with a US address, with a mismatched zip code
* Klarna pops up it’s popup to go through trying to confirm, but it eventually redirects to
a bad URL:
https://YOURSERVER/checkout/Klarna%20Payments%20API%20Error:%20409%20Conflict%20%20Not%20matching%20fields:%20%5Border_amount,%20order_tax_amount,%20order_lines%5B1%5D.total_amount%5D
vs handling the error (either on that redirect or in the popup itself)

Note: Sometimes the listed errors are different, but this is a common one.

Note: We aren’t sure where best to file tickets, so filed at Woocommerce.com as well as here - https://wordpress.org/support/topic/error-page-404ing/#new-topic-0. Sorry for overexposure, just trying to get to the right person as this is causing customer support issues.

**Comment by kristibarbosky** [comment]
covered at: https://wordpress.org/support/topic/error-page-404ing/
