### ISSUE TITLE
Add option to hide klarna pay with invoice

### ISSUE THREAD

**Issue by Chris2011** [krokedil/klarna-payments-for-woocommerce#210]
I added this plugin to woocommerce and I just want to use pay now. For this I used the product "pay now" inside the klarna products. Atm I see Klarna payments like pay now, creditcard and sepa and below there is another one is called invoice. I don't know whether I misunderstand something, but my client doesn't want to offer invoice. Is there an option that I missed to remove inovice from the payments? If there is no option and the invoice payment is optional, please add an option to hide paying with invoice.

**Comment by kristibarbosky** [comment]
Hi @Chris2011  - the Klarna payment methods shown are configured on the merchant's account with Klarna.  To update those (such as remove invoice), please contact Klarna merchant support:  https://docs.krokedil.com/article/304-klarna-contact-merchant-support

**Comment by Chris2011** [comment]
Great thx, I thought I can find this in my klarna account, but couldn't find it. Will ask the merchant support as you mentioned. Thx for your help :)

**Comment by kristibarbosky** [comment]
Hope it all gets sorted quickly for you, happy to (try to) help!

**Comment by Chris2011** [comment]
I believe it will, thx again and I wish you merry christmas and a happy new year :)
