### ISSUE TITLE
Klarna Payments API Error: 400 Bad Request Bad value: order_lines[0].total_amount

### ISSUE THREAD

**Issue by ahsan-shahbaz** [krokedil/klarna-payments-for-woocommerce#217]
![image](https://user-images.githubusercontent.com/59723200/110852150-ccc36580-82d3-11eb-963e-726d764c3a13.png)

Unable to checkout proper through Klarna Payment WP Plugin
**Klarna Payments API Error: 400 Bad Request Bad value: order_lines[0].total_amount**
this error appears when on the final step of my payment process while routing from klarna portal to my checkout page.
Some how order is created but have this in that order notes in wp-admin-> Woocommerce ->orders
![image](https://user-images.githubusercontent.com/59723200/110852626-69860300-82d4-11eb-84c5-7d6a15a66305.png)

**Comment by ahsan-shahbaz** [comment]
> ![image](https://user-images.githubusercontent.com/59723200/110852150-ccc36580-82d3-11eb-963e-726d764c3a13.png)
> 
> Unable to checkout proper through Klarna Payment WP Plugin
> **Klarna Payments API Error: 400 Bad Request Bad value: order_lines[0].total_amount**
> this error appears when on the final step of my payment process while routing from klarna portal to my checkout page.
> Some how order is created but have this in that order notes in wp-admin-> Woocommerce ->orders
> ![image](https://user-images.githubusercontent.com/59723200/110852626-69860300-82d4-11eb-84c5-7d6a15a66305.png)

@mathias-krokedil @slobodan @clifgriffin @NiklasHogefjord @joshuatf

**Comment by NiklasHogefjord** [comment]
This is not a regular bug in the plugin but probably a configuration error. We probably need to look into plugin logs to be able to help you out with this more in detail. Please get in touch with our support at support@krokedil.com and we will help you there.
