### ISSUE TITLE
Allow scripts to be loaded on the one-step checkout page (cart + checkout)

### ISSUE THREAD

**Issue by dalgrang** [krokedil/klarna-payments-for-woocommerce#222]
In klarna-payments-for-woocommerce/classes/class-wc-gateway-klarna-payments.php, `enqueue_scripts()` bails out on cart page, due to this if statement:

```
if ( ! is_checkout() || is_order_received_page() || is_cart() ) {
    return;
}
```

This is causing an issue on the one-step checkout page, where both cart and checkout are existing, as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/57522913/111770092-a6dd2880-88b2-11eb-90c7-8ce5cf58283a.png)

Would it be possible to change the if statement to

```
if ( ! is_checkout() || is_order_received_page() ) {
    return;
}
```

so that, the plugin's scripts can be loaded on the one-step checkout page as well?

**Comment by MichaelBengtsson** [comment]
Closing this since this got released with version 2.5.0
