### ISSUE TITLE
Woocommerce order comments when unsuccsessful

### ISSUE THREAD

**Issue by martinowren** [krokedil/klarna-payments-for-woocommerce#225]
I think there should be implemented a feature that does the following.

When a customer tries to use Klarna, but it gets denied from Klarna, a comment should be added to the WC order object with the reason for denial.

Stripe does this, and it's very helpful for me as a store manager to tell the customer why it failed.

Thanks!

**Comment by zcasparro** [comment]
Hi @martinowren, currently Klarna does not share a customer's denial reason to the merchant. This may change in the future, but is not currently something that our plugin can decide. 

As such, I will close this issue, and will reopen if this changes in the future.
