### ISSUE TITLE
Include a configurable option to include order line item image urls

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#24]
Klarna API now includes a field to pass a product's optional image_url with the order line items (which will enable customers to see the product image in MyKlarna when they are paying for their orders).  When reasonable, can you please add this into the KP plugin? 

This should also be a on/off configurable option in the Woo admin.

For more details, see:
https://developers.klarna.com/api/#payments-api__create-a-new-order__order_lines

**Comment by slobodan** [comment]
@kristibarbosky do we need an option for this? Wouldn't it be cleaner if we just include the image if there is one attached to a product, and not do it otherwise?

**Comment by kristibarbosky** [comment]
In case a merchant does have product URL's but does not want to send them to Klarna, we wanted this to be configurable in the Woo admin tool, but we do want the setting defaulted to on.

**Comment by slobodan** [comment]
Fixed in develop

**Comment by kristibarbosky** [comment]
image_url & product_url are now sent (if configured), see order excerpt below.

one note: originally these weren't sent after uploading the plugin, but after editing & saving the config settings, it did then seem to take effect.

{
  "order_id": "dc8c96cd-03eb-56f1-b918-77553189cfc2",
  "status": "AUTHORIZED",
  "fraud_status": "ACCEPTED",
  "order_amount": 63900,
  "original_order_amount": 63900,
  "captured_amount": 0,
  "refunded_amount": 0,
  "remaining_authorized_amount": 63900,
  "purchase_currency": "USD",
  "locale": "en-US",
  "order_lines": [
    {
      "reference": "222222222",
      "type": "physical",
      "quantity": 1,
      "quantity_unit": "",
      "name": "Bed [Size: TWIN XL]",
      "total_amount": 60000,
      "unit_price": 60000,
      "total_discount_amount": 0,
      "tax_rate": 0,
      "total_tax_amount": 0,
      "merchant_data": null,
      "product_url": "https://wptest.mageklarna.com/product/bed/?attribute_size=TWIN+XL",
      "image_url": "https://wptest.mageklarna.com/wp-content/uploads/2017/01/Bed9-180x180.jpg"
