### ISSUE TITLE
Anchor tag within radio button label is causing label to not work well (when label is moved in front of title)

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#26]
The merchant has customized their theme to display the Klarna logo before the title (i.e. "Pay Over Time").  Because of having an image so close to the radio button, it is causing the radio button to not be selectable the same as the other radio buttons, e.g. the customer has to click the radio button directly and can't select the text as with other radio buttons.

What would be the best option to improve this?  Instead of having the Klarna logo be a link, should we go back to the option of the "What is Klarna?" link with float-right in the label (similar to how PayPal does on GhostBed.com)?  Are there any other, better options to consider?

**Comment by slobodan** [comment]
If they moved it, they should be responsible for it. As I mentioned earlier, a payment gateway is only supposed to return its "icon":

https://docs.woocommerce.com/wc-apidocs/source-class-WC_Payment_Gateway.html#271-281

If we only do that, then it's up to WooCommerce + theme to display it where they want it. Everything else can potentially cause issues likes this.

We can do something similar to what WooCommerce does with PayPal and "What is PayPal?" text, but it's not guaranteed to look good with every merchant's theme, and if that is the goal here, then that's the option I suggest.

**Comment by kristibarbosky** [comment]
If we have the merchant fix this, most likely they will just opt to remove the link on the logo and then Klarna won't have a link on the radio button label; in order to click the link, the customer would have to select the Klarna option.  This isn't ideal, so trying to determine a better option than that.

I thought previously we had pushed the "What is Klarna"/float-right option until after merchant go live, so worth reviewing that option now.   Since both PayPal & Zibby are using the "What is ..?" approach, it doesn't seem like it is such a poor approach for themes.

**Comment by kristibarbosky** [comment]
Per Slack discussion on March 7th, this will be a configurable item about what is the clickable link in the label for the radio button (logo or "What is Klarna?" text).

**Comment by slobodan** [comment]
@kristibarbosky fixed in develop branch.

**Comment by kristibarbosky** [comment]
Test passed successfully.  Logo will no longer be clickable and link will always be displayed.  The checkbox determines if the What is link is floated-right or not.  

One small change to the admin config setting to remove the extra word link at the end of both the label and text:  

"If checked, "What is Klarna?" link will be floated right." **link**"

![what is klarna admin setting](https://cloud.githubusercontent.com/assets/15654455/23752711/75d1d4f2-04a4-11e7-83db-dfd87d11477b.png)
![what is klarna floated right](https://cloud.githubusercontent.com/assets/15654455/23752712/75d20760-04a4-11e7-82e7-f19a0a414696.png)
![what is klarna not floated right](https://cloud.githubusercontent.com/assets/15654455/23752713/75d29b6c-04a4-11e7-816d-26a5227f21ec.png)

**Comment by kristibarbosky** [comment]
![image](https://cloud.githubusercontent.com/assets/15654455/23754104/d56f20e0-04a9-11e7-891e-62647d2aecb9.png)

and updated admin config:
![image](https://cloud.githubusercontent.com/assets/15654455/23754125/e1ba73ae-04a9-11e7-8c9f-7ab6ffb42360.png)
