### ISSUE TITLE
Warning notice in Woo admin if KP plugin activated but OM plugin is not activated

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#27]
If a store has the KP plugin activated, but does not have the OM plugin activated, provide a strong warning message in the Woo admin.

**Comment by slobodan** [comment]
If Klarna Payments is active, but Klarna Order Management is not, this notice will be shown:

![screen shot 2017-03-16 at 11 48 54](https://cloud.githubusercontent.com/assets/129607/23992790/8f43a7f4-0a3e-11e7-9265-5e36e158d4bb.png)

in these pages:

* Edit order
* Any WooCommerce settings page
* Plugins page

Fix is in develop branch.

**Comment by kristibarbosky** [comment]
Awesome!  

![image](https://cloud.githubusercontent.com/assets/15654455/23994735/b33c0f42-0a1c-11e7-95f7-6fbaf3d8e493.png)
