### ISSUE TITLE
Error with address

### ISSUE THREAD

**Issue by moochie07** [krokedil/klarna-payments-for-woocommerce#280]
Hi, we are setting up Klarna on our website for the first time and after doing all the required configuration, when we attempt to place our first order, we get the following error message...."**There has been an error with your address
Please check the following fields: Postal code**" Our Merchant ID is K1244430. Any help would be greatly appreciated. Thank you.

**Comment by montazarr** [comment]
Hello @moochie07

This error message is not from our plugin. Please [contact our support team](support@krokedil.com), they should be able to help you with your issue. I am closing this issue. If you still think this is a bug in our plugin, feel free to re-open the issue again.
