### ISSUE TITLE
Names with an apostrophe or period result in a 409 order conflict error

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#29]
Orders with apostrophe result in a 409 order conflict error:

Last name, such as B'arbosky, see data from logging:

     "shipping_address" : {
        "given_name" : "Kristi",
        "family_name" : "B\\'arbosky",

Name "St. Germain":
    "shipping_address" : {
        "family_name" : "St. Germain",

    "body" : {
      "error_code" : "BAD_VALUE",
      "error_messages" : [ "Not matching fields: [billing_address.family_name, shipping_address.family_name]" ],
      "correlation_id" : "d571e9b9-2735-4829-b01f-b355295f5883"

**Comment by slobodan** [comment]
@kristibarbosky, closed automatically on push, assigning to you for testing

**Comment by kristibarbosky** [comment]
Tests passed successfully, see http://wptest.mageklarna.com/wp-admin/post.php?post=612&action=edit and http://wptest.mageklarna.com/wp-admin/post.php?post=611&action=edit
