### ISSUE TITLE
Support for woocommerce HPOS. Required from August 2023.

### ISSUE THREAD

**Issue by MajorChump** [krokedil/klarna-payments-for-woocommerce#305]
The Klarna plugins are all incompatible with the new HPOS (https://developer.woocommerce.com/2022/09/14/high-performance-order-storage-progress-report/) which will become the default Woocommerce experience from August.

You can check the following on any site by going to 

> /wp-admin/plugins.php?plugin_status=incompatible_with_feature&feature_id=custom_order_tables

If the plugins aren't directly interacting with posts or postmeta it will be a simple case of adding the following to each plugin

`add_action( 'before_woocommerce_init', function() {
	if ( class_exists( \Automattic\WooCommerce\Utilities\FeaturesUtil::class ) ) {
		\Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility( 'custom_order_tables', __FILE__, true );
	}
} );`

(https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#declaring-extension-incompatibility)

**Comment by mntzrr** [comment]
Hello @MajorChump 

Thanks for notifying us about this. We're aware of this, and intend to fix this.
