### ISSUE TITLE
If Klarna returns an error from create_order call, a new auth token must be retrieved before the next create_order call

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#31]
Klarna's create_order is idempotent; if the first create_order call returns an error, subsequent calls to create_order will continue to return the same error code for that same auth token, even if the error is actually resolved.

Therefore, if a new auth token must be retreived before a subsequent create_order call.  

Also, please call release remaining auth on 1st auth token.

**Comment by slobodan** [comment]
Fixed in develop branch.

**Comment by kristibarbosky** [comment]
I cannot test this since I can't force the 409 error.  If I update the order directly (via Postman), as soon as I return to the page, another update_session is called by the plugin.  I can't create the order in error as I don't have the auth token.
