### ISSUE TITLE
Change defaults for some admin settings

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#34]
Please change the defaults for the following fields:
Title => Pay Over Time
Description => Get the flexibility to pay over time with Klarna!
Background => #ffffff
"What is Klarna? link" => checked  
(also, please remove quotes from the What is Klarna? link text)

**Comment by slobodan** [comment]
Fixed in develop

**Comment by kristibarbosky** [comment]
thanks
