### ISSUE TITLE
Release 3.2.0 breaks checkout

### ISSUE THREAD

**Issue by VladimirLi** [krokedil/klarna-payments-for-woocommerce#350]
Hi new release breaks checkout with the following error:
PHP Fatal error:  Uncaught Error: Class 'KP_Subscription' not found in /bitnami/wordpress/wp-content/plugins/klarna-payments-for-woocommerce/classes/class-wc-gateway-klarna-payments.php:251

**Comment by mntzrr** [comment]
Thanks for reporting this. Is this still an issue with version 3.2.1?

**Comment by mntzrr** [comment]
I've checked the code you referenced. I can confirm that this should be fixed with version 3.2.1.

**Comment by VladimirLi** [comment]
Thanks for the prompt response. It works!

**Comment by mntzrr** [comment]
Thanks for confirming this!
