### ISSUE TITLE
Perform Klarna order update before WooCommerce does it

### ISSUE THREAD

**Issue by slobodan** [krokedil/klarna-payments-for-woocommerce#36]
Currently ```woocommerce_saved_order_items``` hook is used, switch to ```woocommerce_before_saved_order_items``` instead. Bigger changes needed, since in woocommerce_before_saved_order_items WC_Order items can't be used.

**Comment by slobodan** [comment]
Applies to Order Management plugin

**Comment by MichaelBengtsson** [comment]
Closed since i belive this has been resolved from testing.
