### ISSUE TITLE
Shared secret needs be encoded when sent to Klarna

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#37]
Unable to create a Klarna Payments session when using a set of credentials that have an ampersand in the secret.

**Comment by kristibarbosky** [comment]
Tested with develop branch.  Still could not create a session with N100208 for US.

**Comment by slobodan** [comment]
Fixed in develop

**Comment by kristibarbosky** [comment]
Test passed successfully, tested with N100208, created order f2b0bf33-7216-5549-8d89-86d0de0ebb22
