### ISSUE TITLE
Show KP iframe with offers if customer selects KP prior to entering customer data

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#41]
Customers would like to see a KP iframe with offers if the customer selects the KP payment option prior to entering their data.   Currently no iframe is displayed prior to a customer entering their complete address data.

Per discussion on Aug. 10, 2017,  if KP is selected, iframe should be loaded with offers. 
 If KP is configured across multiple countries, use geolocation to pull the customer's country.  If KP is not configured across multiple countries, use the store's country.  

(Alternatively,  we could provide a message asking the customer to fill in their customer data, but this would need to be localized, so displaying the KP iframe with offers is preferred.)

**Comment by slobodan** [comment]
Just to recap this (and please correct me if I'm wrong about it):

* Initial .load() is called as soon as checkout is loaded/updated with Klarna Payments being the selected option, customer information fields are not necessary for this
* However, when checkout is loaded, we do not make it possible to click checkout button until all fields are available

This is for all countries, including US, correct?

**Comment by kristibarbosky** [comment]
@slobodan - yes, this is correct (and does work for US too).  just to clarify, load still needs to be called as well based on certain customer address changes and the checkout button should be enabled when minimal necessary address fields are supplied.

**Comment by slobodan** [comment]
Got it. So, there should be more `.load()` call than I suggested?

What if we get the initial load with three (postal code, phone, state) fields missing, then customer enters postal code, then phone, then state? Does this mean we need to fire `.load()` three times as they progress through the fields?

**Comment by slobodan** [comment]
Responding to your comment.

The way it is now, WooCommerce update_checkout (which, when completed will trigger `.load()`) is fired when either one of country, postal code or state is changed. That's WooCommerce functionality, nothing we added. Those changes are the only ones we need to reload the iframe on, correct?

**Comment by slobodan** [comment]
@kristibarbosky 

To summarise what's done now:

* Change country, state or postal code - WooCommerce update_checkout is triggered, when update_checkout is done, we do `.load()`
* Billing phone, billing email - when these two change we trigger `.load()`, there is no WooCommerce update_checkout for those fields

This means we ignore changes to first name, last name, street address etc. but if you leave some of those empty WooCommerce won't let you checkout anyway.

I think that covers everything, but please review.

**Comment by kristibarbosky** [comment]
In order to get the KP offer to load, I should only have to enter the billing_country field and select the radio button, right?  The iframe isn't showing the offer when I do these steps; I still have to enter a full address to get the offer to load.

**Comment by slobodan** [comment]
> Could the iframe default load with the store's base location if the customer hasn't yet entered a billing country yet?

Yes, there's a WooCommerce setting for default customer location, which is what we read server-side and also what billing country field is prepopulated to. Unless they use "No default location" it works. I think if a merchant uses "No default location" we should respect their intent not to guess customer location. Thoughts?

**Comment by kristibarbosky** [comment]
Agreed @slobodan - thanks for the reminder about this setting and yes, we should respect this setting.

**Comment by slobodan** [comment]
Fixed the change phone/email to empty and sorted out the debounce on changes callbacks, current delay is 500ms after the last typed character.

However, and I think this is caused by Klarna, if you enter all the fields and load the iframe, then delete phone (which triggers .load), then the iframe gets reloaded and looks fine still. If you then type anything back you get "Oops something went wrong" in the iframe.

Is there a way to check why this happens?

P.S. It was a US test

**Comment by kristibarbosky** [comment]
Klarna is currently working through additional, updated address validation code, which is not yet live, but will help improve this issue.  

For the current error, our logs show that when the phone is updated with an invalid value, the following log entry:

"Klarna-Correlation-Id" : "ddafc2fc-e643-4e54-8584-29fa635fbd25"
    "status" : "invalid_update",
        "status_details" : {
          "reason" : "internal",
          "invalid_fields" : [ "shipping_address.phone", "billing_address.phone" ]
        }

If the phone field is invalid (i.e. not enough digits), could/should Woo not load the form until the phone is valid?

**Comment by slobodan** [comment]
Woo does not have phone validation, it only checks if the field is empty or not. 

I've tested what triggers the iframe error and it seems to happen (for US) when phone value is 4 characters or shorter. So, for now I'll just add this check (4 or shorter) and only load if the value is long enough, otherwise just disable the field.

**Comment by kristibarbosky** [comment]
Comments above sound good.  Found an issue with testing though:
1. Enter a full address including an invalid zip code (e.g. "43215 CBUS"); Woo returns an invalid zip error.
2. Fix the zip code and place order, received a "409" error and authorize call still sent Klarna the invalid zip value.  (Correlation id: 291b3c70-0d55-4c9a-942f-48830d83cdd6)

**Comment by kristibarbosky** [comment]
Test passed successfully.  After code is merged with master, this ticket can be closed.
