### ISSUE TITLE
Enable KP iframe to be in English for any market

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#42]
Some Woo stores are in English even though the store's base location is not in a native English speaking market, e.g. NL.

Per status call on Aug 17, 2017, to support the KP iframe to be in English (instead of showing a Dutch iframe for an English store with base location==NL), pull the site's Woo language setting, and if English, use English for iframe, else use the standard locale for the market.

**Comment by slobodan** [comment]
Fixed by checking if `get_locale()` ([WordPress function](https://github.com/WordPress/WordPress/blob/6146ba0b3322df67d972789434ca66e22462f8e9/wp-includes/l10n.php#L10-L76)) is en_GB or en_US before checking Klarna purchase country.

**Comment by kristibarbosky** [comment]
Looks great!  Tested with German site (and saw iframe in German) and English site (with German base location) and saw iframe in English.

**Comment by kristibarbosky** [comment]
Klarna product doesn't yet support English for NL, but will fix the current error on authorization to default to the market's default locale (nl for NL).
