### ISSUE TITLE
KP title - enable this field to optionally be localized for each market

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#43]
Still continue to have a single KP title field (defaulted to "Pay Over Time") but additionally have an optional title field for each market that, if filled in, would override the default KP radio button title.

**Comment by slobodan** [comment]
@kristibarbosky what to do with "What is Klarna/Was ist Klarna" link next to it?

Title issue is solved in develop, but does the link need to be localized too?

**Comment by kristibarbosky** [comment]
@slobodan - Since the link is already localized for German, hopefully that will be sufficient still.  What about localizing the Description field though?

**Comment by slobodan** [comment]
Description per country added (develop)

**Comment by kristibarbosky** [comment]
Tests passed.  Closing ticket.  This can be committed to master branch when your changes are all ready.
