### ISSUE TITLE
Send shipment tracking info to Klarna

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#44]
If a Woo store uses the 'official' WooCommerce shipment tracking info extension, only supported for this plugin: https://docs.woocommerce.com/document/shipment-tracking/, send the shipment tracking info to Klarna (could this happen either on capture or after capture depending on how the shipment tracking extension works).

For API info, see https://developers.klarna.com/api/#order-management-api-add-shipping-info-to-a-capture

**Comment by slobodan** [comment]
Is there a merchant with access to this plugin, so we can test it?

**Comment by kristibarbosky** [comment]
Unfortunately I do not have access to this plugin at this time.

**Comment by kristibarbosky** [comment]
Moving to OM plugin instead of KP plugin
