### ISSUE TITLE
KP iframe not reloading enough based on customer address changes

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#45]
Use cases: 

- [ ] changing the billing country (e.g. from NL to a non-supported country, like Nepal), the iframe should reload to reflect that country is not supported.  Recreated on https://wptest.mageklarna.com/woo-checkout/
- [ ] after changing address data (e.g. remove phone number) after the iframe was previously loaded using a complete customer address, should the iframe reload?   Per status call on Aug 17, 2017, the checkout page reloads the iframe when the Woo checkout loads, which then triggers the KP iframe load.  The Woo checkout currently loads when these fields change:  country, state, postal code.

Perhaps this ticket also relates to https://github.com/krokedil/klarna-payments-for-woocommerce/issues/41?  Should the iframe load for EU without any address data?  Then it should update based on billing country changes.  The "Place Order" button should not be enabled until address data is complete still though.

**Comment by slobodan** [comment]
At https://wptest.mageklarna.com/woo-checkout/ checkout does reload when country is changed.

**Comment by kristibarbosky** [comment]
Can not recreate this today.
