### ISSUE TITLE
Reorganize KP config fields in Woo admin screen

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#46]
- [x] add most important fields at top 
- [x] put live credentials above test creds
- [x] put test mode checkbox above market credentials
- [x] alphabetize countries
- [x] change label for MID to Username (to be consistent with terms, as on https://developers.klarna.com/en/us/kco-v3/apply-for-test-account)
- [x] change label of shared secret to Password
- [x] change "Live" to "Production"

**Comment by slobodan** [comment]
@kristibarbosky can you help me figure out which the most important fields are?

I'm trying something to make the page easier to navigate, it still looks ugly, but the functionality is there. The idea is to make sections of the page (credentials per country and iframe options collapsable).

![screen shot 2017-08-21 at 13 24 14](https://user-images.githubusercontent.com/129607/29517184-24b1f7d0-8674-11e7-9329-c45b35058d57.png)

Do you think this makes sense?

**Comment by kristibarbosky** [comment]
@slobodan - yes, I like this approach.  The important fields include the test mode flag, title, & enable checkbox.  Looks like you've got it covered here.

**Comment by slobodan** [comment]
That page says Username is MID + random string, we're referring just to MID as Username, correct?

**Comment by kristibarbosky** [comment]
Previously, merchants just had to enter their MID (e.g. K501043) to authenticate to Klarna, but Klarna is migrating to require the username instead (e.g. K501043_ab3f86778031).  So going forward, merchants will input a username which includes MID, but is longer than the MID.  This username is already in use for production credentials (for about a year now), but the migration to require username instead of MID is happening for test credentials too.

**Comment by kristibarbosky** [comment]
Looks great!  

![image](https://user-images.githubusercontent.com/15654455/29570307-167a6fe8-8724-11e7-8905-66dd2cbb36e4.png)

**Comment by kristibarbosky** [comment]
![image](https://user-images.githubusercontent.com/15654455/29570334-25b09974-8724-11e7-9f9b-a2be547f0687.png)
