### ISSUE TITLE
Add product identifiers to order_line data

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#47]
New order data has been requested for the Klarna API.  

category_path
global_trade_item_number
manufacturer_part_number
brand

For more info, see https://developers.klarna.com/api/#payments-api__create-a-new-credit-session__order_lines__product_identifiers

(After adding this for KP, it should also be added for KCO v3).

**Comment by slobodan** [comment]
Thanks. None of this is mandatory, correct?

**Comment by kristibarbosky** [comment]
@slobodan - Correct, none of these are mandatory.

**Comment by slobodan** [comment]
There's several plugins that provide these fields (Google Product Feed fields), need to decide which one(s) to support.

**Comment by kristibarbosky** [comment]
Per discussion during 24 Aug 2017 weekly status, we want to make this very easy for merchants, so approach is to check for "top 5" (but not all) plugins that support these fields and if available send the data.

**Comment by NiklasHogefjord** [comment]
Closing this for now.
