### ISSUE TITLE
Update Klarna logo to new rebranded logo

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#48]
Update Klarna logo (with radio button for the payment method) from old logo to new logo.

Old: https://cdn.klarna.com/1.0/shared/image/generic/logo/en_us/basic/black.png?width=68
New: https://cdn.klarna.com/1.0/shared/image/generic/logo/en_us/basic/logo_black.png?width=68

![image](https://user-images.githubusercontent.com/15654455/29775177-15bc8444-8bd2-11e7-880b-f5ccc1b631c7.png)

Please also update to Klarna rebranding on both KP & KCO documentation:
https://docs.woocommerce.com/document/klarna/?_ga=2.149226998.130295434.1503587908-1021354840.1497427453
http://docs.krokedil.com/documentation/klarna-payments-woocommerce/

**Comment by slobodan** [comment]
We don't have old logos in documentation, right? Or am I missing something?

**Comment by slobodan** [comment]
Has fix label applies to plugin only

**Comment by kristibarbosky** [comment]
This KCO documentation has a screen shot, under 'Configuring the Klarna Checkout page' section, which needs to be updated pls:
https://docs.woocommerce.com/document/klarna/?_ga=2.149226998.130295434.1503587908-1021354840.1497427453\

I could create a separate github ticket under Klarna Gateway project, but was combining all rebranding changes in this ticket.

KP documentation doesn't currently have a logo, but do you want to add one there at the top of the page perhaps?

**Comment by slobodan** [comment]
Makes perfect sense, updated both pages.

**Comment by kristibarbosky** [comment]
Klarna logo now uses rebranded black logo:
https://cdn.klarna.com/1.0/shared/image/generic/logo/en_us/basic/logo_black.png?width=75

![image](https://user-images.githubusercontent.com/15654455/30075032-a3de05de-9241-11e7-8935-c0db6ada615c.png)
