### ISSUE TITLE
Rounding issue where order total doesn't match sum of all items

### ISSUE THREAD

**Issue by slobodan** [krokedil/klarna-payments-for-woocommerce#49]
This could cause issues when trying to capture the order, if Woo total is higher than Klarna total (which equals sum of all items' totals).

**Comment by slobodan** [comment]
Also fix tax rate (don't calculate, read the data)

**Comment by kristibarbosky** [comment]
Can you also please update the documentation: http://docs.krokedil.com/documentation/klarna-payments-woocommerce/#6

**Comment by kristibarbosky** [comment]
Tested successfully, see order 8f84fb59-dde5-5414-bdd5-7f92d873e919 (for MID N100135).

Also successful for MID K500674 (previously tax_rate was incorrect at 19.05%=1.6 / 8.4 = 0,1904761905 for this order data).
{
    "order_id": "5b0f99c3-3ed6-548c-aaca-70b478fa7a05",
    "order_amount": 1000,
    "purchase_currency": "EUR",
    "order_lines": [
        {
            "quantity": 1,
            "total_amount": 1000,
            "unit_price": 1000,
            "total_discount_amount": 0,
            "tax_rate": 1900,
            "total_tax_amount": 160,

Updates can be merged with master branch.
