### ISSUE TITLE
Admin settings (prescreen) in Woo admin for KP

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#5]
The following settings should to be included in the Klarna Payments Woo admin settings:
1. prescreen enabled (only applicable for the US)
2. iframe color & radius settings, see https://developers.klarna.com/api/#payments-api__create-a-new-session__options

**Comment by slobodan** [comment]
Options added, and color options applied to iframe, the question what to do with prescreen option value remains. Assign the issue back to me when you respond, please.

**Comment by kristibarbosky** [comment]
Config options tested successfully.  Melissa has reached out to the PM regarding prescreen.
