### ISSUE TITLE
Remove "Allow Klarna Payments across multiple countries" in Woo admin

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#50]
**Old:**
Allow Klarna Payments across multiple countries
**New:**
Offer Klarna Payments across multiple countries?

**Old:**
 If this option is checked Klarna credentials for customer's billing country will be used, if available. If those credentials are not available, then Klarna credentials for shop base location country will be used. If the option is unchecked only Klarna credentials for shop base location country will be used.

**New:**
If checked, credentials for Klarna Payments will be used for each country where credentials are entered.  If not checked, only the shop's base location country's credentials will be used.  

**Or possibly just delete this option from the admin page and just use credentials that are entered?  We could then add an explanation above the countries list: "Only enter credentials for countries that are covered per your contract with Klarna. "

**Comment by slobodan** [comment]
Let's discuss some more today, but I agree deleting the option might be better for merchants.

**Comment by kristibarbosky** [comment]
Per discussion with Melissa & Slobodan & Kristi during weekly status, we all agree that we'll remove the "Allow Klarna Payments across multiple countries" setting.  The code will just automatically use any credentials that are entered (across multiple countries if entered).  

We'll cover with training and documentation that if credentials are entered for a country where currency or credentials aren't configured per Klarna contract, an error (e.g. could not create Klarna session) will be thrown.  So each country in production should be explicitly tested (with customer addresses for that country).

**Comment by slobodan** [comment]
To summarize the change, previously if you had the option unchecked, the country for which Klarna credentials were used was shop base country, otherwise it was customer billing country (WooCommerce figures out what this is, we just read it).

With the change, it is always customer country. @kristibarbosky please take a look, and confirm that was the idea and I'll merge the changes.

**Comment by kristibarbosky** [comment]
@slobodan - Yes, let's proceed.  I will test of course, but I believe if credentials aren't entered for the customer's billing country, the KP payment option will just not be displayed.   If the customer clicks the KP radio button prior to entering a billing country, KP may or may not display, depending on the Woo setting for "Default customer location".  thx!

**Comment by slobodan** [comment]
Thanks. Fix merged into develop.

**Comment by kristibarbosky** [comment]
Test passed successfully:
- KP is not shown for a country if currency isn't supported
- KP changes based on country selected
- KP uses General setting "Default customer location" to determine if KP should be shown or not when no address is entered
