### ISSUE TITLE
locale is always set to 'en-US' even when store's base location != US

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#51]
(this may be related to recent code changes, but not sure which ticket, perhaps #50, so just creating a new ticket).

The locale is always set to 'en-us' regardless of the store's base location.  (The iframe title, description, & language are still displayed in the matching language for market, e.g. Dutch for Netherlands store though.)

Order data: 
{
    "order_id": "a2bd52d7-c92c-5f2e-a693-9eb7be890c32",
    "order_amount": 21775,
    "purchase_currency": "EUR",
    "locale": "en-US",

![image](https://user-images.githubusercontent.com/15654455/30074926-42345b8a-9241-11e7-8b28-8c6b9f434369.png)

**Comment by kristibarbosky** [comment]
Spoke with product lead for Klarna Payments today, and en-us is not an acceptable locale for non-US stores. For example, a Dutch store wanting to display the KP iframe in English, should use locale==en-nl.

**Comment by krokedilmartin** [comment]
Hi @johngamalo 
Please contact our support here with this question: https://krokedil.com/support/

**Comment by johngamalo** [comment]
Hi, @krokedilmartin. Thanks for the heads up! :)
