### ISSUE TITLE
Capture failed with error - Object of class WP_Error could not be converted to string

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#54]
![gabbinelli capture error](https://user-images.githubusercontent.com/15654455/31190017-d6490f3c-a907-11e7-9ce7-7b3c36cd9370.png)

This error did not happen prior to Klarna integration.  I have requested logs and environment access, but could the code be updated to better handle and display the actual error?  I did not see any Splunk data for the capture that came to Klarna, so likely the error happened prior to calling Klarna.

**Comment by slobodan** [comment]
Added more error handling to OM plugin, update should be automatic from backend. 

Would be good to be able to see full stack for this error, if they have access to it, though.

**Comment by kristibarbosky** [comment]
can be closed, working now
