### ISSUE TITLE
no longer use Klarna.Credit.initialized

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#55]
Instead of using Klarna.Credit.initialized, follow documentation at:
https://developers.klarna.com/en/us/kco-v3/klarna-payment-methods/2-present-the-klarna-widget

**Comment by slobodan** [comment]
Seems like all it took was to remove Klarna.Credit.initialized part of if statement, everything else already follows the documentation.

@kristibarbosky can you please review?

**Comment by kristibarbosky** [comment]
Seems to test fine, but to help me understand better, where in the code do you call Klarna.Credit.init()?

**Comment by slobodan** [comment]
It's in gateway PHP class:

https://github.com/krokedil/klarna-payments-for-woocommerce/blob/master/includes/class-wc-gateway-klarna-payments.php#L603
https://github.com/krokedil/klarna-payments-for-woocommerce/blob/master/includes/class-wc-gateway-klarna-payments.php#L672

**Comment by kristibarbosky** [comment]
thanks.  good to merge to master branch & close ticket.
