### ISSUE TITLE
Update KP documentation to include PHP version requirements

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#56]
Update http://docs.krokedil.com/documentation/klarna-payments-woocommerce/ to include the PHP version requirements (5.5 or higher).

A merchant tried to use the KP plugin with a version of PHP lower than 5.5 and got this error:

Fatal error: Can't use method return value in write context in /home4/ab98685/public_html/merchant.com/wp-content/plugins/klarna-payments-for-woocommerce-master/includes/class-wc-klarna-payments-order-lines.php on
line 191

**Comment by slobodan** [comment]
I'll update the document, but WooCommerce recommended PHP is 7, and the only place where I can find minimum requirement is here (5.6 for WC 2.6):

https://silicondales.com/tutorials/woocommerce-tutorials/minimum-requirements-woocommerce/

Adding the note to our docs, but I don't think this should be an issue for us.
