### ISSUE TITLE
Could the "What is Klarna?" text be configurable?

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#57]
We have a DE store where the site is in English.  So the "Was ist Klarna?" link text is in German but the rest of the site is in English.  Could we make this configurable?
![buckleandseam kristi oct 13th](https://user-images.githubusercontent.com/15654455/31552474-9f47340a-b005-11e7-9dcf-174389b76633.png)

**Comment by slobodan** [comment]
If possible, we should try to avoid adding another setting field, so how about trying to read site locale and showing text based on that?

**Comment by johannesclaudi** [comment]
Sounds good to me. But we should have a fallback solution "en" in place as well in case we don't support the locale of the site.

**Comment by kristibarbosky** [comment]
Kristi agrees.

**Comment by kristibarbosky** [comment]
![what is klarna german store english language](https://user-images.githubusercontent.com/15654455/32375801-4a1fef24-c079-11e7-8cf6-4827d5ef538c.png)
![was is klarna german](https://user-images.githubusercontent.com/15654455/32375803-4a91bf32-c079-11e7-88be-822459abf12e.png)
