### ISSUE TITLE
KP doesn't work for all currencies with "WooCommerce Price Based on Country (Basic)" currency switcher

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#58]
If customer i is creating a german order from US geolocation, the Woo KP code is trying to pull US KP credentials and not the german ones. The error message in the frontend can be found in the appendix.  There are no US credentials for this store.  This issue can be recreated in our test store.

![image](https://user-images.githubusercontent.com/15654455/31772795-bb75894e-b4ae-11e7-9887-b7db06d6dc67.png)

**Comment by slobodan** [comment]
The attached image is too small, can you upload bigger one (if it has any meaningful details in it)?

What's the currency in this scenario?

**Comment by kristibarbosky** [comment]
I currently have set my store base location to Netherlands, Default Customer location to "Geolocate"; and have no US credentials (at http://wptest.mageklarna.com).  Only with this  "WooCommerce Price Based on Country (Basic)" active do I get the red error message at checkout "Could not create Klarna session, please refresh the page to try again"

**Comment by kristibarbosky** [comment]
https://drive.google.com/a/klarna.com/file/d/0B3epxj0q3t5qSjlaWG5PaTdhSDQ/view?usp=sharing

**Comment by kristibarbosky** [comment]
Test passed successfully on test store (http://wptest.mageklarna.com).

**Comment by kristibarbosky** [comment]
This can be closed once the code is merged with master branch.  Fixed on buckleandseam now.
