### ISSUE TITLE
Add filter for to allow merchants to customize retrieving KP credentials

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#60]
A merchant has customized to split out UK country into separate countries (England, Wales, Scotland, Northern Ireland), so they need to be able to customize how GB credentials are pulled.  Per discussion, please add a filter to WC()->customer->get_billing_country() at:

https://github.com/krokedil/klarna-payments-for-woocommerce/blob/master/includes/class-wc-gateway-klarna-payments.php#L1187

**Comment by kristibarbosky** [comment]
Tested by adding the following code snippet to /wordpresstest/public_html/wp-content/themes/storefront/functions.php (which isn't where this code should live in production, but is sufficient for testing):

 add_filter( 'wc_klarna_payments_country', 'test_kp_country_override' );
 
 function test_kp_country_override( $variable ) {
     // logic would be added here to set country correctly
      return 'US';
 }

This enabled a US KP iframe to be displayed for all addresses (e.g. Canada), but then the iframe correctly returned an error on authorize, see correlation_id: 8d97f7b6-11e7-4fc1-a46d-fa6545a85756

"body" : {
      "internal" : {
        "status" : "country_not_supported",
        "status_details" : {
          "reason" : "internal"
        }

**Comment by NiklasHogefjord** [comment]
Sorry if I'm asking questions that actually should know the answer of here @kristibarbosky :). 

Is this a matter of adding Canada as a new supported country to KP or are there more places in the plugin we need to be able to filter country to get this feature actually working?

**Comment by kristibarbosky** [comment]
@NiklasHogefjord - no worries - all questions are good for clarity!

Canada isn't actually a supported KP country [yet].  For this scenario (Canadian store base address with Canadian customer address), "country not supported" is the appropriate response.  It does work as desired for a Canadian store with a customer using a US address, which uses US credentials.

No further action at this; I was just documenting my comments relating to this case.
