### ISSUE TITLE
Add setting to show/hide What is Klarna link in checkout [PI-557]

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-payments-for-woocommerce#63]
Since Klarna is a well known payment provider in the Nordics, I think it should be possible for merchants to remove the "What is Klarna" link in checkout. 

Would it be ok to add a setting for this @kristibarbosky?

**Comment by kristibarbosky** [comment]
Yes, agreed @NiklasHogefjord .  Good point, thanks!

**Comment by kristibarbosky** [comment]
@MichaelBengtsson - another request for this ticket came in today: PI-557
