### ISSUE TITLE
Implement /payments endpoint (instead of using /credit endpoint)

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#64]
The Klarna Payments documentation for the new /payments endpoint is now documented on klarna.developers.com and is the default endpoint presented.  With the new /payments endpoint, [payment_method_categories](https://developers.klarna.com/api/#payments-api__merchant_session__payment_method_categories) are returned.  Using the /payments endpoint, multiple Klarna payment options can be displayed in a store's payment options.  

https://developers.klarna.com/api/#payments-api__merchant_session__payment_method_categories

**Comment by kristibarbosky** [comment]
Here are is an example:

 "payment_method_categories" : [ {
        "identifier" : "pay_later",
        "name" : "Pay Later",
        "asset_urls" : {
          "descriptive" : "https://cdn.klarna.com/1.0/shared/image/generic/badge/de_de/pay_later/descriptive/pink.svg",
          "standard" : "https://cdn.klarna.com/1.0/shared/image/generic/badge/de_de/pay_later/standard/pink.svg"
        }
      }, {
        "identifier" : "direct_debit",
        "name" : "Direct Debit",
        "asset_urls" : {
          "descriptive" : "https://cdn.klarna.com/1.0/shared/image/generic/badge/de_de/direct_debit/descriptive/pink.svg",
          "standard" : "https://cdn.klarna.com/1.0/shared/image/generic/badge/de_de/direct_debit/standard/pink.svg"
        }
      }, {
        "identifier" : "direct_bank_transfer",
        "name" : "Direct Bank Transfer",
        "asset_urls" : {
          "descriptive" : "https://cdn.klarna.com/1.0/shared/image/generic/badge/de_de/direct_bank_transfer/descriptive/pink.svg",
          "standard" : "https://cdn.klarna.com/1.0/shared/image/generic/badge/de_de/direct_bank_transfer/standard/pink.svg"
        }
      }, {
        "identifier" : "pay_over_time",
        "name" : "Pay Over Time",
        "asset_urls" : {
          "descriptive" : "https://cdn.klarna.com/1.0/shared/image/generic/badge/de_de/pay_over_time/descriptive/pink.svg",
          "standard" : "https://cdn.klarna.com/1.0/shared/image/generic/badge/de_de/pay_over_time/standard/pink.svg"
        }
      }

**Comment by kristibarbosky** [comment]
@slobodan - is it possible to remove Title & Description from the KP config settings?  and only use the name returned from create_session?  (Currently if I remove the Title value, no payment method is noted on the confirmation page.)

![image](https://user-images.githubusercontent.com/15654455/37440665-ff2247f2-27d3-11e8-8a23-2d75373e63db.png)


Also, update_session will be changed to also return the payment_method_categories array.  Once that change is made, we'll need to read and use that data also.

**Comment by slobodan** [comment]
It's possible to remove it, but I'm not sure if that would break something.

Assigning this one to @MichaelBengtsson to investigate.

**Comment by kristibarbosky** [comment]
@MichaelBengtsson  - Klarna engineering has advised us to do a read_session API call after the update_session API call to pull in the correctly up-to-date payment_method_categories.  When time permits, can you update the code and we can test this approach?  thanks!

**Comment by kristibarbosky** [comment]
@MichaelBengtsson - Today Klarna has released the update where /payments read_session now includes the payment_method_categories array:

"correlation_id" : "da76d0c8-f43b-4ce9-b216-8d52a25c1c91"
"payment_method_categories" : [ {
        "identifier" : "pay_later",
        "name" : "Pay later.",
        "asset_urls" : {
          "descriptive" : "https://cdn.klarna.com/1.0/shared/image/generic/badge/en_us/pay_later/descriptive/pink.svg",
          "standard" : "https://cdn.klarna.com/1.0/shared/image/generic/badge/en_us/pay_later/standard/pink.svg"
        }
      }

So when a customer has changed their order, we need to read the session to catch when the payment_method_categories may have changed.

**Comment by kristibarbosky** [comment]
@MichaelBengtsson  - Also worth noting if you haven't already encountered this: if the payment_method_categories array is empty, such as if the customer's address is for a country that is not supported for the MID, then the payment_method_categories array (which would be empty) is not included in the read_session response.
