### ISSUE TITLE
Create PR (pull request) for WooCommerce to treat PR (Puerto Rico) & other territories as US state

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#65]
While Klarna can't yet support orders in Puerto Rico, this licensing is in progress.  Once that is in place, for Klarna to accept the KP order, Puerto Rico must be a state/region within country==US.  Vanilla WooCommerce treats Puerto Rico as a country, not a US state.

A Woo store can be customized to change this so that PR is listed as a US state instead.  (Note: Magento & Shopify already treat Puerto Rico (and others) as a US state.)

The steps below work to customize Woo to support this, but would it be worthwhile to ask for a pull request for Woo so that this will become standard Woo?  If you agree, could you help create that?

As covered at http://www.terrytsang.com/tutorial/woocommerce/add-modify-states-for-woocommerce-checkout-form, customize the list of US states.  
After the above update, change their WooCommerce-General settings:
set store's base address appropriately: https://github.com/woocommerce/theme-customisations

Set shipping & billing countries appropriately in Woo admin.  Note: the merchant should test this fully to verify any impact to shipping methods and other functionality on their site.

Also referenced:
https://github.com/Automattic/woocommerce-services/issues/1129

**Comment by MichaelBengtsson** [comment]
@Nickigreen The issue you have is a WooCommerce issue. There is however a filter that you can use to get arround the issue. You can read about that here: https://docs.woocommerce.com/document/addmodify-states/

**Comment by Nickigreen** [comment]
Perfect! Just what I was looking for. Thank you.


________________________________

**Comment by NiklasHogefjord** [comment]
Closing this. It's probably a WooCommerce issue to solve.
