### ISSUE TITLE
KP order cannot be created due to invalid surcharge tax for iamcasie.de

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#66]
Per create_session request below, for https://www.iamcasie.de/wp-admin, the surcharge tax isn't handled correctly and therefore order_tax_amount is rejected by Klarna.  

	 message:	 {
  "correlation_id" : "6519ba08-308b-4494-b0cb-40343d97c4a5",
  "merchant_id" : "K501862",
  "operation" : "create_session",
  "build_version" : "1.0.20180116083726",
  "request" : {
    "timestamp" : "2018-01-17T15:07:29Z",
    "method" : "POST",
    "path" : "credit/merchant/K501862/v1/sessions",
    "headers" : {
      "Accept" : "*/*",
      "Klarna-Correlation-Id" : "6519ba08-308b-4494-b0cb-40343d97c4a5",
      "User-Agent" : "WordPress/4.7.9; https://www.iamcasie.de - KP:1.4",
      "Referer" : "https://api.playground.klarna.com/credit/v1/sessions",
      "X-Forwarded-Host" : "api.playground.klarna.com",
      "X-Forwarded-Proto" : "http",
      "X-Forwarded-For" : "37.17.229.190, 37.17.229.190, 10.228.41.156",
      "Host" : "api.playground.klarna.com",
      "Accept-Encoding" : "deflate, gzip",
      "Content-Length" : "803",
      "X-Forwarded-Port" : "80",
      "X-Amzn-Trace-Id" : "Root=1-5a5f66b1-5bbca1f405eed71a552f8c12",
      "Content-Type" : "application/json"
    },
    "body" : {
      "purchase_country" : "DE",
      "purchase_currency" : "EUR",
      "locale" : "de-de",
      "order_amount" : 2680,
      "order_tax_amount" : 366,
      "order_lines" : [ {
        "reference" : "188077",
        "name" : "Pocket ID - Couple Casie (Melina Transparent) [Handymodell: Samsung Galaxy A3 2016, Textfarbe: Schwarz, Herzfarbe: Schwarz, Name 01: ji, Name 02: ni]",
        "quantity" : 1,
        "unit_price" : 1995,
        "tax_rate" : 1900,
        "total_amount" : 1995,
        "total_tax_amount" : 319,
        "total_discount_amount" : 0
      }, {
        "type" : "shipping_fee",
        "reference" : "flat_rate:5",
        "name" : "Versandkosten für Warenwert unter 39€",
        "quantity" : 1,
        "unit_price" : 390,
        "tax_rate" : 0,
        "total_amount" : 390,
        "total_tax_amount" : 0
      }, {
        "type" : "surcharge",
        "reference" : "Fee",
        "name" : "Zahlungsgebühr",
        "quantity" : 1,
        "unit_price" : 47.12,
        "tax_rate" : 1900,
        "total_amount" : 47.12,
        "total_discount_amount" : 0,
        "total_tax_amount" : 47.12
      } ]
    }
  },
  "response" : {
    "timestamp" : "2018-01-17T15:07:29Z",
    "status" : 400,
    "headers" : {
      "Render-Time" : "1",
      "Klarna-Correlation-Id" : "6519ba08-308b-4494-b0cb-40343d97c4a5",
      "Content-Type" : "application/json"
    },
    "body" : {
      "error_code" : "BAD_VALUE",
      "error_messages" : [ "Bad value: order_lines[2].total_tax_amount" ],
      "correlation_id" : "6519ba08-308b-4494-b0cb-40343d97c4a5"
    }

**Comment by slobodan** [comment]
Can't reproduce this one, using same plugin they do (Booster for WooCommerce) to add a fee that's configured the same way their fee is, tried checking out with US and non-US as base address and it worked.

**Comment by slobodan** [comment]
@kristibarbosky OK to close?

**Comment by kristibarbosky** [comment]
iamcasie.de did have a successful create_order, but we did not hear the update or resolution (per PI-180). closing this ticket and will reopen if necessary
