### ISSUE TITLE
KP doesn't load.

### ISSUE THREAD

**Issue by Orhn** [krokedil/klarna-payments-for-woocommerce#70]
KP doesn't load if another payment method is enabled such as Cash On Delivery. If disabled it loads without an issue.

WC: 3.3.5 — WP: 4.9.4 — PHP: 7.2.3 — KP: 1.4.2 — MID: K502521

Screen record:
[Klarna.zip](https://github.com/krokedil/klarna-payments-for-woocommerce/files/1859465/Klarna.zip)

**Comment by kristibarbosky** [comment]
Per logs in Klarna and the provided movie, it seems that KP is stuck in an infinite loop of load/payment_methods calls, see screen shot below.  I can not recreate this on my test server, with "Cash On Delivery" enabled.    @Orhn - does this still happen if all other plugins are deactivated except Klarna & WooCommerce plugins?

![image](https://user-images.githubusercontent.com/15654455/38089071-31358c6e-332c-11e8-914a-8b0f5ab2c4a3.png)

The Woo KP iframe is reloaded whenever something triggers the update_checkout Woo JS event.  Is there something on the site that is triggering that update_checkout event?  

Other things that trigger an load of the KP iframe:

1. customer leaves the browser tab and then returns to the tab, see https://github.com/krokedil/klarna-payments-for-woocommerce/blob/master/assets/js/klarna-payments.js#L307-L314
2. when email has been filled in and its a valid email
3. when changing to Klarna payments as a payment method

**Comment by Orhn** [comment]
I'm using official Product Add-Ons and Product Bundles plugin along with iThemes Security.

I have disabled all other plugins except the ones I listed above.

I can't seem to find any other event that triggers KP iframe. It happens right away when the user is on checkout.

Also when enabling Stripe causes the same issue.

Console log has these errors:

[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403)
(api.js.map, line 0)

[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403)
(common-b3e56d8071306f54d0f0.js.map, line 0)

[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403)
(main-2d407d96d039efc0e8f4.js.map, line 0)

[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403)
(locale-sv_SE-43d00f6eeaa9efb73ab8.chunk.js.map, line 0)

[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403)
(fullscreen-99fb21bd198e2ae06118.js.map, line 0)

**Comment by MichaelBengtsson** [comment]
Hi,

Could you please send a support ticket to info@krokedil.se with a wp-admin login? I cant reproduce the error you have on our side.

**Comment by Orhn** [comment]
Of course. Will do as soon as we get a fix on our domain name. Thanks.

All the best,
Orhan.

On 5 Apr 2018, at 14:57, MichaelBengtsson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Could you please send a support ticket to info@krokedil.se<mailto:info@krokedil.se> with a wp-admin login? I cant reproduce the error you have on our side.

**Comment by Orhn** [comment]
Issue was caused from customised – form checkout – template. Reverted back to original file and it works now.
