### ISSUE TITLE
KP images - resize appropriately & use a fallback URL if asset_url is broken

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#80]
As discussed on Slack (https://klarnakrokedil.slack.com/archives/C3PRHCWP7/p1529928870000031), 
1. resize the KP pink badge (as it is too big on some themes)
2. until Klarna fixes that sometimes non-working URLs are returned for asset_urls (per https://jira.int.klarna.net/jira/browse/YACO-2088), use a fallback URL for each payment_method_category:, e.g.: https://cdn.klarna.com/1.0/shared/image/generic/badge/sv_se/pay_later/standard/pink.svg
sv_se works for each payment_method_category: pay_now, pay_later, and slice_it

**Comment by NiklasHogefjord** [comment]
Closing this since it has been released.
