### ISSUE TITLE
Enable merchants to customize a filter to control when KP payment methods are displayed

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#83]
Can you provide documentation and a filter to allow merchants to customize when KP options are displayed to customers?  e.g. a US merchant would like to not display Slice It for low cart values.

**Comment by kristibarbosky** [comment]
for reference: https://www.google.com/url?q=https://businessbloomer.com/woocommerce-disable-payment-method-for-specific-category/&sa=D&source=hangouts&ust=1532691843190000&usg=AFQjCNGT5AiF4vWmVXsLNICv25gOtiEwxw

**Comment by kristibarbosky** [comment]
Niklas added a filter and committed that to the Develop branch for KP.
And I've created a gist here: https://gist.github.com/krokedilgists/4b39e525ca972e0fd1214d148932d994
I've tested that in our demo store (not active anymore) and it did work

**Comment by NiklasHogefjord** [comment]
The commit a24f9678f489101f331100287db28eafef03c534 (released in https://github.com/krokedil/klarna-payments-for-woocommerce/releases/tag/1.5.3) is now live. Closing this issue.
