### ISSUE TITLE
There has been an error with your address (using Myparcel shipping plugin)

### ISSUE THREAD

**Issue by Marienernl** [krokedil/klarna-payments-for-woocommerce#84]
We've switched from the depreciated Klarna Gateway to this plugin,but without success.

We have an active API, and all seems well, but when a customer wants to place an order, it shows

There has been an error with your address

Please check the following fields:
Street address

Support on Klarna's end says the Address information is not properly forwarded towards Klarna.

Help??

**Comment by kristibarbosky** [comment]
Can you please provide your merchant id  (e.g. K100123) and the address that was used so we can review the Klarna logs?

**Comment by Marienernl** [comment]
53157 - http://bit.ly/2mGRarH

**Comment by kristibarbosky** [comment]
Great @Marienernl 
The street_address sent to Klarna is empty:

"country" : "NL",
          "region" : "",
          "postal_code" : "4332XM",
          "city" : "Middelburg",
          "street_address" : "",
          "street_address2" : ""

Does your store have customizations to the Woo checkout form that change the street_address fields?

**Comment by Marienernl** [comment]
Not that we know off. Other forms of payment work correctly fyi.

Is there anything from our end that we can test? /other than temporarily changing the theme.

**Comment by NiklasHogefjord** [comment]
This seems to be a compatibility issue between the Klarna Payments plugin and the Myparcel plugin. Is this the plugin you are using @Marienernl 
https://wordpress.org/plugins/woocommerce-myparcel/ ?

In the plugin we need to send the customer address information to Klarna. To do this we use the standard WooCommerce checkout fields (https://github.com/krokedil/klarna-payments-for-woocommerce/blob/master/includes/class-wc-gateway-klarna-payments.php#L911-L922). But the Myparcel plugin seem to change this and add new checkout fields for the customer address.

If you can confirm that this is the plugin you're using then I can take a closer look and see how we can proceed with trying to make the two plugins compatible.

**Comment by Marienernl** [comment]
@NiklasHogefjord Yes that is the one. Myparce is used by many in The Netherlands, so it would be great if the Klarna plugin could pick up on the extra fields to get the address.

**Comment by NiklasHogefjord** [comment]
Thanks @Marienernl! 

I will look into this but we need to have an internal discussion on how to handle these kinds of compatibility issues. There might be a lot of plugins that stores order data in different customized ways and we should probably look into which ones of these we need to add support for.

To solve the issue that you have right now I introduced a new filter in the array containing the order data sent to Klarna. Via this filter you have the possibility to add address, house number and house number suffix from the fields added by the My Parcel plugin. 

The name of the filter is called _kp_wc_api_request_args_ and can be used in the following way:

`add_filter('kp_wc_api_request_args', 'my_kp_wc_api_request_args', 10, 3 );

function my_kp_wc_api_request_args( $request_args, $order, $posted_data ) {
 	
  	$request_args['billing_address']['street_address'] = $posted_data['billing_address_1'] . ' ' . $posted_data['billing_street_name'] . ' ' . $posted_data['billing_house_number'] . ' ' . $posted_data['billing_house_number_suffix'];
  	$request_args['shipping_address']['street_address'] = $posted_data['shipping_address_1'] . ' ' . $posted_data['shipping_street_name'] . ' ' . $posted_data['shipping_house_number'] . ' ' . $posted_data['shipping_house_number_suffix'];
	return $request_args;
}`

**Comment by NiklasHogefjord** [comment]
Oh, and this filter is not live yet. You need to download and use the plugin from the Develop branch here: https://github.com/krokedil/klarna-payments-for-woocommerce/tree/develop.

**Comment by Marienernl** [comment]
@NiklasHogefjord Thanks for getting back to me on this. Which file exactly should I replace? Or should I download the entire plugin.

**Comment by Marienernl** [comment]
@NiklasHogefjord I've downloaded the development version as a whole, installed it, but it still seems to be giving the address error. Any suggestions?

**Comment by Marienernl** [comment]
Hi @NiklasHogefjord, I've forwarded Myparcel to this issue, see if you both can come up with a working solution. I haven't seen it work yet. :( Its been 1.5 weeks since we last used Klarna. So we are basically not able to offer Klarna payments to our customers.

**Comment by NiklasHogefjord** [comment]
Hi @Marienernl, I will try to get you an addon-plugin that will help solve your problem during this week.

**Comment by Marienernl** [comment]
@NiklasHogefjord that would be great. Thanks so much.

**Comment by NiklasHogefjord** [comment]
@Marienernl I've updated the code example in the gist now so it fetches the data from the order instead. If you're running WooCommerce v3.x it should fetch the meta fields for _billing_street_name, _billing_house_number, _shipping_street_name & _shipping_house_number correctly.

https://gist.github.com/krokedilgists/a53a087f2b21702368aa75cb0eca108c

**Comment by Marienernl** [comment]
Hi @NiklasHogefjord, thank you for getting back on this. Either im doing something wrong, or its not working. I've installed the develop branch to our site, enabled it, but it keeps bugging about:

There has been an error with your address

Please check the following fields:
Street address

What am I doing wrong?

**Comment by Pixelstart** [comment]
I'm experiencing the exact same issue as @Marienernl. Please fix this.

**Comment by NiklasHogefjord** [comment]
@Marienernl Just to be sure that you are using the code example as described in the gist I also created a plugin that you could use: https://www.dropbox.com/s/3svmw1ku8p5vojl/klarna-payments-myparcel.zip?dl=0

If that doesn't solve your problem I need to look into this more in detail. I don't have a MyParcel account myself so I would need access to a temporary WP admin login to your site to be able to troubleshoot this.

Please get in touch with us at support@krokedil.se for further communication regarding the login credentials.

**Comment by Marienernl** [comment]
Hi @NiklasHogefjord Thank you for the effort, but im afraid im still getting the dreaded:

There has been an error with your address

Please check the following fields:
Street address

I will send an email with our credentials and see if you can figure out what the issue is.

**Comment by Marienernl** [comment]
@NiklasHogefjord  its been a while since we heard back. It's been weeks now without payment afterwards. i know we are not the only business around, but this is frustrating to say the least. I've send an email to support days ago.

**Comment by NiklasHogefjord** [comment]
Hi @Marienernl & @Pixelstart,
After more testing I realize that address data is sent to Klarna both _before_ the order is created in Woo (via javascript events in front end) and _after_ the order has been created in Woo.

The code I've provided so far have only been for _after_ the order has been created in Woo.

I have now implemented a new filter that can be used for the frontend/javascript communication. I have an updated version of the MyParcel compatibility plugin here: https://gist.github.com/krokedilgists/a53a087f2b21702368aa75cb0eca108c (can be downloaded as a zip directly here: https://gist.github.com/krokedilgists/a53a087f2b21702368aa75cb0eca108c/archive/28ce322e9b1930d1016859c58868e733bb1c8338.zip).

To be able to use it you also need the latest version of the Klarna plugin from the Develop branch here: https://github.com/krokedil/klarna-payments-for-woocommerce/tree/develop.

**Comment by Marienernl** [comment]
Hi @NiklasHogefjord I appreciate the help.

We are getting somewhere, but unfortunately it now says 

Option not available

Unfortunately this option is not available. Please choose a different payment method. 

after adding my date of birth and trying to fulfill an order. 

Will the changes to the plugin be added to the release version? I hate using dev plugins on a working site.

**Comment by kristibarbosky** [comment]
@Marienernl @NiklasHogefjord - "Option not available" is a common Klarna response, but does indicate that the address data is working now.  I recommend testing further with test credentials, not live credentials, as that is easy to be approved by Klarna and complete orders (without incurring fees and such).

If there are still questions or concerns with approvals, please contact your Klarna implementation advisor and they can help work through the reason for the message.

**Comment by kristibarbosky** [comment]
Closing this ticket as the merchant has now been able to go live with KP; please reopen if further support is needed.

**Comment by Marienernl** [comment]
@NiklasHogefjord Is it normal for the plugin to export all order information to Klarna even if they are not fulfilled by a klarna payment method? I've been checking the logs in the merchant login and I see that Klarna captures all order information.  As far as I can see this is all anonymized, no customer data is send through, but still?

**Comment by NiklasHogefjord** [comment]
Hi @Marienernl, yes the cart information is sent to Klarna even if the purchase is not finalized with Klarna as the selected payment method.

The reason for this is because the contents of the cart (or the cart value) determines which Klarna payment methods that should be available/visible for the customer in the checkout.

**Comment by Marienernl** [comment]
@NiklasHogefjord  alright. When can I update to the latest stable build? For it to work with the compatibility plugin?

**Comment by MichaelBengtsson** [comment]
@Marienernl This has been added in the 1.6.0 release. So you can update to that version now.
