### ISSUE TITLE
Cannot hide Klarna banner

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#88]
KCO module has a neat 'X' in the top right corner to hide Klarna banner in Woo admin, but KP doesn't.

Can this be added? 

![image](https://user-images.githubusercontent.com/15654455/43406512-5dfbdf36-93ea-11e8-9f9f-bcf325e22da7.png)

**Comment by NiklasHogefjord** [comment]
Absolutely. I'll add this.

**Comment by NiklasHogefjord** [comment]
Fixed in 69489e7ae6a207c63bad04a962174ac1936e8393 (and released in https://github.com/krokedil/klarna-payments-for-woocommerce/releases/tag/1.5.3)
