### ISSUE TITLE
"Invalid Payment Method" error when placing KP order (PI-437)

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#92]
An "Invalid Payment Method" error is shown when the Klarna is chosen  and the customer attempts to place the order.  No create_order calls have been made for the merchant as of yet; although many authorization attempts.  No errors appear in the Klarna logs; we are able to see an authorization token being created but then no create_order API call is made.  

![image](https://user-images.githubusercontent.com/15654455/44285154-3bcaa180-a232-11e8-850e-d0e97677a4fb.png)

Sending link to a downloadable, duplicated copy of the store.

(I have already requested the merchant to update their WooCommerce & PHP versions, as there are also order total mismatch errors between Woo & Klarna when there is an order with a discount.)

The store (WC Version: 3.0.6) is NOT on the latest version of Woo (v3.4.4); merchant is using PHP Version: 7.1.5

Here are excerpts from a sample order (fffb91c3-b269-6d92-ab40-e59bb3f086e7):

"purchase_country" : "US",
      "purchase_currency" : "USD",
      "locale" : "en-us",
      "order_amount" : 84150,
      "order_tax_amount" : 4950,
      "order_lines" : [ {
        "quantity" : 8,
        "unit_price" : 9900,
        "tax_rate" : 0,
        "total_amount" : 79200,
        "total_tax_amount" : 0,
        "total_discount_amount" : 0,
      }, {
        "type" : "shipping_fee",
        "reference" : "local_pickup:1",
        "quantity" : 1,
        "unit_price" : 0,
        "tax_rate" : 0,
        "total_amount" : 0,
        "total_tax_amount" : 0
      }, {
        "type" : "sales_tax",
        "reference" : "Sales Tax",
        "name" : "Sales Tax",
        "quantity" : 1,
        "unit_price" : 4950,
        "tax_rate" : 0,
        "total_amount" : 4950,
        "total_discount_amount" : 0,
        "total_tax_amount" : 0
      } ]

**Comment by kristibarbosky** [comment]
@NiklasHogefjord - the merchant has now updated their PHP version (see updated User-Agent below), and hopefully/likely their WooCommerce version too, but they are still getting the "Invalid Payment Method" error.   

“Klarna-Correlation-Id” : “5b7c2dd9-8c82-4572-bd12-7cbf8f01a0e2",
     “User-Agent” : “WordPress/4.9.8; https://****.com - KP:1.5.2 - PHP Version: 7.1.21 - Krokedil”,

**Comment by NiklasHogefjord** [comment]
This seems to be related with the WooCommerce version installed. The merchant is running v 3.0.6. V 3.4.x does not have this issue. Will investigate the required WC version a bit closer.

**Comment by kristibarbosky** [comment]
PI-437 has been closed.

**Comment by NiklasHogefjord** [comment]
Updated required WC version in cc469da6969e720ef5a702662781d6fda0e0c5b0
