### ISSUE TITLE
Support Germanized plugin - don't allow customer payment without legal terms accepts

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#95]
I've asked Klarna DE implementation advisors for more specifics regarding what exactly needs to be supported for KP, but one issue that was raised: 
Customer can complete KP order without agreeing the the terms & conditions checkouts.  This checkbox is configured as required in the Germanized plugin.  Can KP honor that?

**Comment by NiklasHogefjord** [comment]
When it comes to honoring terms checkboxes I think that this is all handled by WooCommerce. We don't handle any terms related stuff for the regular terms & conditions checkbox.

If they have an issue with this it would be great to get access to a staging site where we can troubleshoot. I've tried to set up the Germanized plugin but it is in large parts in German (the correct way to develop a plugin distributed on wordpress.org is to develop it in English and then translate it to German) and there is six different settings pages available. It is therefor a bit tough to setup :).

**Comment by kristibarbosky** [comment]
The Germanized plugin is free to download at https://wordpress.org/plugins/woocommerce-germanized/

**Comment by kristibarbosky** [comment]
Closing this ticket (since https://github.com/krokedil/klarna-payments-for-woocommerce/issues/112 also covers this request).

**Comment by kristibarbosky** [comment]
PI-452
