### ISSUE TITLE
Change payment gateway name on checkout

### ISSUE THREAD

**Issue by BastianBickelhaupt** [krokedil/klarna-payments-for-woocommerce#96]
Hello, on settings i cannot set a custom title to change the displayed payment gateway title at checkout. How can i change it? Inside the documentation i see an input field "title", but i dont see this in the current plugin version.

thanks

**Comment by kristibarbosky** [comment]
@BastianBickelhaupt  - 
When Klarna Payments first was released, the title shown to the customer as checkout was configurable within the Woo admin, but Klarna now returns the appropriate payment name(s)/title(s) that should be displayed within checkout.  Thus the Klarna Payments offers' titles are no longer configurable.

**Comment by BastianBickelhaupt** [comment]
Ok thanks ...
